### ISSUE TITLE
TypeError: 'NoneType' object cannot be interpreted as an integer; libbitsandbytes_cpu.so: undefined symbol: cget_managed_ptr

### ISSUE THREAD

**Issue by 18782961008** [InternLM/xtuner#118]
执行xtuner train internlm_chat_7b_qlora_lawyer_e3 --deepspeed deepspeed_zero2_offload
 加载完数据后报错

硬件：两张24G P40显卡
系统：ubuntu20.04
python：3.10
cuda:11.8
nvcc -v:10.1
transformers: 4.33.1
bitsandbytes ：  0.40.0
bitsandbytes-windows2.0.0+cu118： 0.37.5
torch:2.0.0+cu118

报错详细信息：

[2023-09-12 21:25:12,865] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.10.3, git-hash=unknown, git-branch=unknown
[2023-09-12 21:25:12,865] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-09-12 21:25:12,865] [INFO] [comm.py:652:init_distributed] Not using the DeepSpeed or dist launchers, attempting to detect MPI environment...
[2023-09-12 21:25:12,936] [INFO] [comm.py:702:mpi_discovery] Discovered MPI settings of world_rank=0, local_rank=0, world_size=1, master_addr=192.168.2.140, master_port=29500
[2023-09-12 21:25:12,937] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2023-09-12 21:25:14,190] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
[2023-09-12 21:25:14,194] [INFO] [logging.py:96:log_dist] [Rank 0] Removing param_group that has no 'params' in the client Optimizer
[2023-09-12 21:25:14,194] [INFO] [logging.py:96:log_dist] [Rank 0] Using client Optimizer as basic optimizer
[2023-09-12 21:25:14,290] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Basic Optimizer = PagedAdamW32bit
[2023-09-12 21:25:14,290] [INFO] [utils.py:54:is_zero_supported_optimizer] Checking ZeRO support for optimizer=PagedAdamW32bit type=<class 'bitsandbytes.optim.adamw.PagedAdamW32bit'>
[2023-09-12 21:25:14,290] [WARNING] [engine.py:1149:_do_optimizer_sanity_check] **** You are using ZeRO with an untested optimizer, proceed with caution *****
[2023-09-12 21:25:14,290] [INFO] [logging.py:96:log_dist] [Rank 0] Creating torch.float16 ZeRO stage 2 optimizer
[2023-09-12 21:25:14,290] [INFO] [stage_1_and_2.py:146:__init__] Reduce bucket size 100000000
[2023-09-12 21:25:14,290] [INFO] [stage_1_and_2.py:147:__init__] Allgather bucket size 100000000
[2023-09-12 21:25:14,290] [INFO] [stage_1_and_2.py:148:__init__] CPU Offload: True
[2023-09-12 21:25:14,290] [INFO] [stage_1_and_2.py:149:__init__] Round robin gradient partitioning: False
Rank: 0 partition count [1] and sizes[(159907840, False)] 
[2023-09-12 21:25:15,933] [INFO] [utils.py:803:see_memory_usage] Before initializing optimizer states
[2023-09-12 21:25:15,934] [INFO] [utils.py:804:see_memory_usage] MA 13.97 GB         Max_MA 13.97 GB         CA 14.04 GB         Max_CA 14 GB 
[2023-09-12 21:25:15,934] [INFO] [utils.py:811:see_memory_usage] CPU Virtual Memory:  used = 7.31 GB, percent = 5.8%
Traceback (most recent call last):

Traceback (most recent call last):
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/xtuner/tools/train.py", line 246, in <module>
    main()
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/xtuner/tools/train.py", line 242, in main
    runner.train()
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1180, in train
    self.strategy.prepare(
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 181, in prepare
    self.model = self._wrap_model(model)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 196, in _wrap_model
    engine, self.optim_wrapper.optimizer, *_ = deepspeed.initialize(
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 303, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1213, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1467, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 516, in __init__
    self.initialize_optimizer_states()
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 651, in initialize_optimizer_states
    self.optimizer.step()
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 266, in step
    self.init_state(group, p, gindex, pindex)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 401, in init_state
    state["state1"] = self.get_state_buffer(p, dtype=torch.float32)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 309, in get_state_buffer
    buff = F.get_paged(*p.shape, dtype=dtype, device=p.device)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/bitsandbytes/functional.py", line 171, in get_paged
    cuda_ptr = lib.cget_managed_ptr(ct.c_size_t(num_bytes))
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cget_managed_ptr

**Comment by 18782961008** [comment]
我怀疑是cuda和torch版本问题，于是重装了cuda 和cudatoolkit版本都换为11.7，torch相关库也与InternLM的torch.txt版本一致。再执行xtuner train internlm_chat_7b_qlora_lawyer_e3 --deepspeed deepspeed_zero2_offload后报错如下：

Rank: 0 partition count [1] and sizes[(159907840, False)] 
[2023-09-12 22:54:26,840] [INFO] [utils.py:803:see_memory_usage] Before initializing optimizer states
[2023-09-12 22:54:26,840] [INFO] [utils.py:804:see_memory_usage] MA 13.97 GB         Max_MA 13.97 GB         CA 14.04 GB         Max_CA 14 GB 
[2023-09-12 22:54:26,841] [INFO] [utils.py:811:see_memory_usage] CPU Virtual Memory:  used = 8.83 GB, percent = 7.1%
Traceback (most recent call last):
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/xtuner/tools/train.py", line 246, in <module>
    main()
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/xtuner/tools/train.py", line 242, in main
    runner.train()
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1180, in train
    self.strategy.prepare(
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 181, in prepare
    self.model = self._wrap_model(model)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 196, in _wrap_model
    engine, self.optim_wrapper.optimizer, *_ = deepspeed.initialize(
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 303, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1213, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1467, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 516, in __init__
    self.initialize_optimizer_states()
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 651, in initialize_optimizer_states
    self.optimizer.step()
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 268, in step
    self.prefetch_state(p)
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 320, in prefetch_state
    F.prefetch_tensor(state['state1'])
  File "/home/tfswx/anaconda3/envs/internlm-env/lib/python3.10/site-packages/bitsandbytes/functional.py", line 187, in prefetch_tensor
    lib.cprefetch(get_ptr(A), ct.c_size_t(num_bytes), ct.c_int32(deviceid))
TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by LZHgrla** [comment]
`PagedAdamW32bit` 与 `offload_optimizer` 并不兼容，您可以考虑以下两种解决办法
1. 关闭 `offload_optimizer`，即使用`--deepspeed deepspeed_zero2`。因为是 QLoRA，优化器占用的显存是非常有限的，故关闭后不会带来额外的极端开销
2. 关闭 `PagedAdamW32bit`，使用 `torch.optim.AdamW`，即在 `config` 中将 `optim_type` 设为 `torch.optim.AdamW`

建议关闭 `offload_optimizer`，以获得最快的训练速度

**Comment by 18782961008** [comment]
thank you!问题已解决！

**Comment by 18782961008** [comment]
> `PagedAdamW32bit` 与 `offload_optimizer` 并不兼容，您可以考虑以下两种解决办法
> 
> 1. 关闭 `offload_optimizer`，即使用`--deepspeed deepspeed_zero2`。因为是 QLoRA，优化器占用的显存是非常有限的，故关闭后不会带来额外的极端开销
> 2. 关闭 `PagedAdamW32bit`，使用 `torch.optim.AdamW`，即在 `config` 中将 `optim_type` 设为 `torch.optim.AdamW`
> 
> 建议关闭 `offload_optimizer`，以获得最快的训练速度

thank you!问题已解决！
