### ISSUE TITLE
pip install xtuner 完后，依然显示ModuleNotFoundError: No module named 'xtuner'

### ISSUE THREAD

**Issue by starkgao** [InternLM/xtuner#132]
(venv) PS G:\ai\xtuner> xtuner list-cfg
G:\ai\xtuner\venv\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Traceback (most recent call last):
  File "G:\ai\xtuner\venv\lib\site-packages\xtuner\tools\list_cfg.py", line 4, in <module>
    from xtuner.configs import cfgs_name_path
ModuleNotFoundError: No module named 'xtuner'
(venv) PS G:\ai\xtuner>

**Comment by starkgao** [comment]
(venv) PS G:\ai\Baichuan2> xtuner list-cfg   

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: G:\ai\Baichuan2\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary G:\ai\Baichuan2\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Traceback (most recent call last):
  File "G:\ai\Baichuan2\venv\lib\site-packages\xtuner\tools\list_cfg.py", line 4, in <module>
    from xtuner.configs import cfgs_name_path
ModuleNotFoundError: No module named 'xtuner'
(venv) PS G:\ai\Baichuan2>
