### ISSUE TITLE
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.

### ISSUE THREAD

**Issue by Sun0308** [InternLM/xtuner#136]
when run: !xtuner chat internlm/internlm-7b --adapter internlm_7b_qlora_colorist/epoch_1_hf --prompt-template colorist
some errors happened:
2023-09-22 07:01:14.626725: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-09-22 07:01:21.715312: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xtuner/tools/chat.py", line 263, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/xtuner/tools/chat.py", line 136, in main
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3187, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3308, in _load_pretrained_model
    raise ValueError(
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.

**Comment by LZHgrla** [comment]
We can add `offload_folder` for `from_pretrained`

This error is fixed on https://github.com/InternLM/xtuner/pull/140
