### ISSUE TITLE
[pth2hf Error]KeyError: 'transformers.AutoModelForCausalLM.from_pretrained is not in the xtuner::builder registry.

### ISSUE THREAD

**Issue by vansin** [InternLM/xtuner#151]
```shell
(xtuner) ➜  xtuner git:(main) ✗ python xtuner/tools/model_converters/pth_to_hf.py work_dirs/internlm_20b_qlora_oasst1_512_e3/internlm_20b_qlora_oasst1_512_e3.py work_dirs/internlm_20b_qlora_oasst1_512_e3/epoch_3.pth work_dirs/internlm_20b_qlora_arxiv_gentitle_e3/hf
[2023-10-01 04:48:16,040] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 108, in <module>
    main()
  File "xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 85, in main
    model = BUILDER.build(cfg.model)
  File "miniconda/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "miniconda/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "xtuner/xtuner/model/sft.py", line 24, in __init__
    self.llm = self._build_from_cfg_or_module(llm)
  File "xtuner/xtuner/model/sft.py", line 75, in _build_from_cfg_or_module
    return BUILDER.build(cfg_or_mod)
  File "miniconda/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "miniconda/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'transformers.AutoModelForCausalLM.from_pretrained is not in the xtuner::builder registry. Please check whether the value of `transformers.AutoModelForCausalLM.from_pretrained` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```

**Comment by LZHgrla** [comment]
This error can be fixed with these tow PRs
MMEngine：https://github.com/open-mmlab/mmengine/pull/1345
XTuner： https://github.com/InternLM/xtuner/pull/141

But, these PRs are not merged into new released up to now. 

While, we can use the original config, instead of the auto-saved config to prevent this error!

**Comment by LZHgrla** [comment]
These tow PRs have been merged!
