### ISSUE TITLE
xtuner train configs/internlm_7b_qlora_alpaca_internlm_assistant.py  found error

### ISSUE THREAD

**Issue by abelezm** [InternLM/xtuner#160]
```python
(xtuner) root@4cf1efcc4830:/store/home_workspace# xtuner train configs/internlm_7b_qlora_alpaca_internlm_assistant.py
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
[2023-10-07 18:05:31,692] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-07 18:05:33,690] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
Traceback (most recent call last):
  File "/store/home_workspace/xtuner/xtuner/tools/train.py", line 246, in <module>
    main()
  File "/store/home_workspace/xtuner/xtuner/tools/train.py", line 87, in main
    cfg = Config.fromfile(args.config)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/config/config.py", line 456, in fromfile
    lazy_import is None and not Config._is_lazy_import(filename):
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/config/config.py", line 1656, in _is_lazy_import
    codes_str = f.read()
  File "/root/miniconda3/envs/xtuner/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 1616: invalid continuation byte
(xtuner) root@4cf1efcc4830:/store/home_workspace#
```

**Comment by LZHgrla** [comment]
Could you please post your config and MMEngine version, so that we can check it!

**Comment by abelezm** [comment]
```python
(xtuner) root@4cf1efcc4830:~# python -c "import mmengine;print(mmengine.__version__)"
0.8.5
(xtuner) root@4cf1efcc4830:~# 
```

**Comment by abelezm** [comment]
```python
quantization_config convert to <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>
10/12 05:03:03 - mmengine - WARNING - Failed to search registry with scope "mmengine" in the "builder" registry tree. As a workaround, the current "builder" registry in "xtuner" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmengine" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "/store/home_workspace/xtuner/xtuner/tools/train.py", line 246, in <module>
    main()
  File "/store/home_workspace/xtuner/xtuner/tools/train.py", line 235, in main
    runner = Runner.from_cfg(cfg)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 445, in from_cfg
    runner = cls(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 412, in __init__
    self.model = self.build_model(model)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 819, in build_model
    model = MODELS.build(model)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/store/home_workspace/xtuner/xtuner/model/sft.py", line 24, in __init__
    self.llm = self._build_from_cfg_or_module(llm)
  File "/store/home_workspace/xtuner/xtuner/model/sft.py", line 75, in _build_from_cfg_or_module
    return BUILDER.build(cfg_or_mod)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 560, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2614, in from_pretrained
    raise ImportError(
ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` 
(xtuner) root@4cf1efcc4830:/store/home_workspace# 
```

**Comment by abelezm** [comment]
after I have "~# pip install accelerate     ~# pip install bitsandbytes    ~# pip install -i https://test.pypi.org/simple/ bitsandbytes"   ,

**Comment by LZHgrla** [comment]
@abelezm  Please try `python -m bitsandbytes` and paste the report.

**Comment by abelezm** [comment]
```python
(xtuner) root@4cf1efcc4830:/store/home_workspace# python -m bitsandbytes
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-12.2/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-12.2/compat/lib.real/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++


++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
+++++++ /usr/local/cuda/compat/lib.real/ CUDA PATHS ++++++++
/usr/local/cuda/compat/lib.real/libcuda.so
+++++++++++++ /usr/local/cuda/lib64 CUDA PATHS +++++++++++++


++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
COMPUTE_CAPABILITIES_PER_GPU = []
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

Torch not compiled with CUDA enabled

Above we output some debug information. Please provide this info when creating an issue via https://github.com/TimDettmers/bitsandbytes/issues/new/choose ...

(xtuner) root@4cf1efcc4830:/store/home_workspace#
```

**Comment by abelezm** [comment]
```python
(xtuner) root@58e5664cf56e:/store/home_workspace# python -m bitsandbytes
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.7/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.7/compat/lib.real/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++


++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
+++++++++++++ /usr/local/cuda/lib64 CUDA PATHS +++++++++++++

+++++++ /usr/local/cuda/compat/lib.real/ CUDA PATHS ++++++++
/usr/local/cuda/compat/lib.real/libcuda.so

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
COMPUTE_CAPABILITIES_PER_GPU = []
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

Torch not compiled with CUDA enabled

Above we output some debug information. Please provide this info when creating an issue via https://github.com/TimDettmers/bitsandbytes/issues/new/choose ...

(xtuner) root@58e5664cf56e:/store/home_workspace# 
```

**Comment by abelezm** [comment]
```python
docker run -itd --gpus all -v /data2/workspace/dockerdir/xtuner/xtuner_1/stwork:/stwork -v /data2/workspace/dockerdir/xtuner/xtuner_1/store:/store -p 0.0.0.0::8888 -p 0.0.0.0::6006 -p 0.0.0.0::8080 -p 0.0.0.0::8081 -p 0.0.0.0::8082 -p 0.0.0.0::7070 -p 0.0.0.0::7071 -p 0.0.0.0::22 -p 0.0.0.0::8000 -p 0.0.0.0::8001 -p 0.0.0.0::8002 -p 0.0.0.0::5000 --name xtuner_1 --ipc=host --privileged=true nvcr.io/nvidia/tensorrt:22.08-py3
```

**Comment by abelezm** [comment]
```python
(xtuner) root@2db8e56be2a3:/store/home_workspace# python -m bitsandbytes
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.7/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.7/compat/lib.real/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++


++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['7.5']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!
(xtuner) root@2db8e56be2a3:/store/home_workspace# 
```

**Comment by abelezm** [comment]
Now，I have the error：

```python
(xtuner) root@2db8e56be2a3:/store/home_workspace# xtuner convert merge     $NAME_OR_PATH_TO_LLM     $NAME_OR_PATH_TO_ADAPTER     $SAVE_PATH     --max-shard-size 2GB
[2023-10-14 16:25:59,300] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/store/home_workspace/xtuner/xtuner/tools/model_converters/merge.py", line 58, in <module>
    main()
  File "/store/home_workspace/xtuner/xtuner/tools/model_converters/merge.py", line 33, in main
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
    resolved_config_file = cached_file(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/root/llm/internlm-7b'. Use `repo_type` argument if needed.
(xtuner) root@2db8e56be2a3:/store/home_workspace# 
```

**Comment by abelezm** [comment]
```python
(xtuner) root@2db8e56be2a3:/store/home_workspace# python3 -m lmdeploy.lite.apis.calibrate \
>   --model $HF_MODEL \
>   --calib_dataset 'c4' \
>   --calib_samples 128 \
>   --calib_seqlen 1024 \
>   --work_dir $HOME_WORKSPACE/w4a16_workdir
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.18s/it]
Loading calibrate dataset ...
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/datasets/load.py:2089: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=False' instead.
  warnings.warn(
Repo card metadata block was not found. Setting CardData to empty.
/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/datasets/load.py:2089: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=False' instead.
  warnings.warn(
Repo card metadata block was not found. Setting CardData to empty.
Traceback (most recent call last):
  File "/root/miniconda3/envs/xtuner/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/xtuner/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/lite/apis/calibrate.py", line 110, in <module>
    fire.Fire(calibrate)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/lite/apis/calibrate.py", line 101, in calibrate
    calib_ctx.calibrate(all_data)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/lite/quantization/calibration.py", line 285, in calibrate
    _ = model(data.to(self.device))
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-7b/modeling_internlm.py", line 579, in forward
    layer_outputs = decoder_layer(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/lite/quantization/calibration.py", line 166, in _forward
    out = self._ori_forwards[mod](*batch_args[i],
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-7b/modeling_internlm.py", line 293, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-7b/modeling_internlm.py", line 197, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
(xtuner) root@2db8e56be2a3:/store/home_workspace# 
```

**Comment by abelezm** [comment]
8核 32GB 5Mbps

系统盘：高性能云硬盘
网络：[Default-VPC](https://console.cloud.tencent.com/vpc/vpc?rid=25&unVpcId=vpc-apndstfg)

显卡：nvidia T4

**Comment by LZHgrla** [comment]
Hi @abelezm 
You can transfer the above `python3 -m lmdeploy.lite.apis.calibrate` error to lmdeploy repo https://github.com/InternLM/lmdeploy/issues

Also, has the error with `bitsandbytes` been solved?

**Comment by ybdesire** [comment]
also get the error, and the error cannot be fixed by install the reported libs.

```
ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes`

```

**Comment by LZHgrla** [comment]
@ybdesire Hi,
It seems that the  installation of `bitsandbytes` has some problems, and I recommend that you can report an issue in its repo
https://github.com/TimDettmers/bitsandbytes/issues

**Comment by LZHgrla** [comment]
@ybdesire  Hi!
One possible solution is to re-install the PyTorch by coda
```
conda install -y pytorch=2.0.1 torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
pip install xtuner
```
