### ISSUE TITLE
使用本地internlm-20b-chat进行Qlora微调报错并且如何在两张3090上进行分布式训练,请教如何解决，感谢！

### ISSUE THREAD

**Issue by backatonesJ** [InternLM/xtuner#172]
终端命令：xtuner train configs/internlm_20b_qlora_internlm_assistant.py
模型路径和数据路径如下：pretrained_model_name_or_path = '/root/xtuner/internlm-20b-chat'
alpaca_zh_path='/root/xtuner/examples/toy_data/toy_custom_single_turn_data.json'
报错如下：
Traceback (most recent call last):
  File "/root/xtuner/xtuner/tools/train.py", line 246, in <module>
    main()
  File "/root/xtuner/xtuner/tools/train.py", line 235, in main
    runner = Runner.from_cfg(cfg)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 442, in __init__
    self.register_hooks(default_hooks, custom_hooks)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1995, in register_hooks
    self.register_custom_hooks(custom_hooks)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1976, in register_custom_hooks
    self.register_hook(hook)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1877, in register_hook
    hook_obj = HOOKS.build(hook)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/xtuner/xtuner/engine/hooks/dataset_info_hook.py", line 10, in __init__
    self.tokenizer = BUILDER.build(tokenizer)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 738, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2017, in from_pretrained
    return cls._from_pretrained(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2249, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-20b-chat/tokenization_internlm.py", line 68, in __init__
    super().__init__(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 367, in __init__
    self._add_tokens(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 467, in _add_tokens
    current_vocab = self.get_vocab().copy()
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-20b-chat/tokenization_internlm.py", line 108, in get_vocab
    vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-20b-chat/tokenization_internlm.py", line 96, in vocab_size
    return self.sp_model.get_piece_size()
AttributeError: 'InternLMTokenizer' object has no attribute 'sp_model'

**Comment by backatonesJ** [comment]
请问这个报错的原因是与transformer的版本有关吗 我们的transformer版本是4.34.1
