### ISSUE TITLE
【issue when finetune on MS-agent】TypeError: eval() arg 1 must be a string, bytes or code object

### ISSUE THREAD

**Issue by maxchiron** [InternLM/xtuner#205]
## Reproduce
```Bash
xtuner train internlm_7b_qlora_msagent_react_e3_gpu8_copy.py
```

## stdout
```bash
 --------------------
2023-11-05 10:19:26,048 - modelscope - INFO - PyTorch version 2.1.0 Found.
2023-11-05 10:19:26,048 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-11-05 10:19:26,082 - modelscope - INFO - Loading done! Current index file version is 1.9.4, with md5 4ddb5f111efbb5cb5faa1a094cfb053a and a total number of 945 components indexed
/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/datasets/load.py:1748: FutureWarning: 'ignore_verifications' was deprecated in favor of 'verification_mode' in version 2.9.1 and will be removed in 3.0.0.
You can remove this warning by passing 'verification_mode=no_checks' instead.
  warnings.warn(
Found cached dataset json (/root/.cache/modelscope/hub/datasets/json/MSAgent-Bench-2d6f40b9336f9424/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
  0%|                                                                            | 0/2 [00:00<?, ?it/s]/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by mode='default'.
  table = cls._concat_blocks(blocks, axis=0)
100%|███████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 130.60it/s]
Traceback (most recent call last):
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/tools/train.py", line 257, in <module>
    main()
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/tools/train.py", line 253, in main
    runner.train()
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1160, in train
    self._train_loop = self.build_train_loop(
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 965, in build_train_loop
    loop = EpochBasedTrainLoop(
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 824, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/dataset/modelscope.py", line 16, in process_ms_dataset
    return process_hf_dataset(dataset, *args, **kwargs)
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/dataset/huggingface.py", line 77, in process_hf_dataset
    dataset = dataset.map(dataset_map_fn)
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 580, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 545, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3087, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3441, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3344, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/xtuner/dataset/map_fns/dataset_map_fns/msagent_map_fn.py", line 52, in msagent_react_map_fn
    text = eval(example['conversations'])
TypeError: eval() arg 1 must be a string, bytes or code object
```

* In xxx_copy.py, I only changed pretrained model path to local path.

**Comment by vansin** [comment]
please paste the config in issue

**Comment by maxchiron** [comment]
> please paste the config in issue
> 
> which platform does the model download? modelscope, huggingface or openxlab

## Model Downloaded from ModelScope

## Config contents
```python
# Copyright (c) OpenMMLab. All rights reserved.
import torch
from bitsandbytes.optim import PagedAdamW32bit
from mmengine.dataset import DefaultSampler
from mmengine.hooks import (CheckpointHook, DistSamplerSeedHook, IterTimerHook,
                            LoggerHook, ParamSchedulerHook)
from mmengine.optim import AmpOptimWrapper, CosineAnnealingLR
from modelscope.msdatasets import MsDataset
from peft import LoraConfig
from transformers import (AutoModelForCausalLM, AutoTokenizer,
                          BitsAndBytesConfig)

from xtuner.dataset import process_ms_dataset
from xtuner.dataset.collate_fns import default_collate_fn
from xtuner.dataset.map_fns import (msagent_react_map_fn,
                                    template_map_fn_factory)
from xtuner.engine import DatasetInfoHook, EvaluateChatHook
from xtuner.model import SupervisedFinetune
from xtuner.utils import PROMPT_TEMPLATE

#######################################################################
#                          PART 1  Settings                           #
#######################################################################
# Model
pretrained_model_name_or_path = 'internlm-chat-7b-v1_1'

# Data
data_path = 'damo/MSAgent-Bench'
prompt_template = PROMPT_TEMPLATE.default
max_length = 2048
pack_to_max_length = False

# Scheduler & Optimizer
batch_size = 8  # per_device
accumulative_counts = 1
dataloader_num_workers = 2
max_epochs = 3
optim_type = PagedAdamW32bit
lr = 2e-4
betas = (0.9, 0.999)
weight_decay = 0
max_norm = 1  # grad clip

# Evaluate the generation performance during the training
evaluation_freq = 500
SYSTEM = (
    '你是一个可以调用外部工具的助手，可以使用的工具包括：\n'
    "{{\'GoogleSearch\': \'一个可以从谷歌搜索结果的API。\\n"
    '当你需要对于一个特定问题找到简短明了的回答时，可以使用它。\\n'
    "输入应该是一个搜索查询。\\n\\n\',"
    "\'PythonInterpreter\': \"用来执行Python代码。代码必须是一个函数，\\n"
    "函数名必须得是 \'solution\'，代码对应你的思考过程。代码实例格式如下：\\n"
    '```python\\n# import 依赖包\\nimport xxx\\ndef solution():'
    '\\n    # 初始化一些变量\\n    variable_names_with_real_meaning = xxx'
    '\\n    # 步骤一\\n    mid_variable = func(variable_names_with_real_meaning)'
    '\\n    # 步骤 x\\n    mid_variable = func(mid_variable)\\n    # 最后结果'
    '\\n    final_answer =  func(mid_variable)\\n    return final_answer'
    "\\n```\\n\"}}\n"
    '如果使用工具请遵循以下格式回复：\n```\n'
    'Thought:思考你当前步骤需要解决什么问题，是否需要使用工具\n'
    "Action:工具名称，你的工具必须从 [[\'GoogleSearch\', \'PythonInterpreter\']] 选择"
    '\nAction Input:工具输入参数\n```\n工具返回按照以下格式回复：\n'
    '```\nResponse:调用工具后的结果\n```'
    '\n如果你已经知道了答案，或者你不需要工具，请遵循以下格式回复\n```'
    '\nThought:给出最终答案的思考过程\nFinal Answer:最终答案\n```\n开始!\n')
evaluation_inputs = ['上海明天天气怎么样？']

#######################################################################
#                      PART 2  Model & Tokenizer                      #
#######################################################################
tokenizer = dict(
    type=AutoTokenizer.from_pretrained,
    pretrained_model_name_or_path=pretrained_model_name_or_path,
    trust_remote_code=True,
    padding_side='right')

model = dict(
    type=SupervisedFinetune,
    llm=dict(
        type=AutoModelForCausalLM.from_pretrained,
        pretrained_model_name_or_path=pretrained_model_name_or_path,
        trust_remote_code=True,
        torch_dtype=torch.float16,
        quantization_config=dict(
            type=BitsAndBytesConfig,
            load_in_4bit=True,
            load_in_8bit=False,
            llm_int8_threshold=6.0,
            llm_int8_has_fp16_weight=False,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type='nf4')),
    lora=dict(
        type=LoraConfig,
        r=64,
        lora_alpha=16,
        lora_dropout=0.1,
        bias='none',
        task_type='CAUSAL_LM'))

#######################################################################
#                      PART 3  Dataset & Dataloader                   #
#######################################################################
train_dataset = dict(
    type=process_ms_dataset,
    dataset=dict(type=MsDataset.load, dataset_name=data_path),
    tokenizer=tokenizer,
    max_length=max_length,
    dataset_map_fn=msagent_react_map_fn,
    template_map_fn=dict(
        type=template_map_fn_factory, template=prompt_template),
    remove_unused_columns=True,
    shuffle_before_pack=True,
    pack_to_max_length=pack_to_max_length)

train_dataloader = dict(
    batch_size=batch_size,
    num_workers=dataloader_num_workers,
    dataset=train_dataset,
    sampler=dict(type=DefaultSampler, shuffle=True),
    collate_fn=dict(type=default_collate_fn))

#######################################################################
#                    PART 4  Scheduler & Optimizer                    #
#######################################################################
# optimizer
optim_wrapper = dict(
    type=AmpOptimWrapper,
    optimizer=dict(
        type=optim_type, lr=lr, betas=betas, weight_decay=weight_decay),
    clip_grad=dict(max_norm=max_norm, error_if_nonfinite=False),
    accumulative_counts=accumulative_counts,
    loss_scale='dynamic',
    dtype='float16')

# learning policy
# More information: https://github.com/open-mmlab/mmengine/blob/main/docs/en/tutorials/param_scheduler.md  # noqa: E501
param_scheduler = dict(
    type=CosineAnnealingLR,
    eta_min=lr * 0.1,
    by_epoch=True,
    T_max=max_epochs,
    convert_to_iter_based=True)

# train, val, test setting
train_cfg = dict(by_epoch=True, max_epochs=max_epochs, val_interval=1)

#######################################################################
#                           PART 5  Runtime                           #
#######################################################################
# Log the dialogue periodically during the training process, optional
custom_hooks = [
    dict(type=DatasetInfoHook, tokenizer=tokenizer),
    dict(
        type=EvaluateChatHook,
        tokenizer=tokenizer,
        every_n_iters=evaluation_freq,
        evaluation_inputs=evaluation_inputs,
        system=SYSTEM,
        prompt_template=prompt_template)
]

# configure default hooks
default_hooks = dict(
    # record the time of every iteration.
    timer=dict(type=IterTimerHook),
    # print log every 100 iterations.
    logger=dict(type=LoggerHook, interval=10),
    # enable the parameter scheduler.
    param_scheduler=dict(type=ParamSchedulerHook),
    # save checkpoint per epoch.
    checkpoint=dict(type=CheckpointHook, interval=1),
    # set sampler seed in distributed evrionment.
    sampler_seed=dict(type=DistSamplerSeedHook),
)

# configure environment
env_cfg = dict(
    # whether to enable cudnn benchmark
    cudnn_benchmark=False,
    # set multi process parameters
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    # set distributed parameters
    dist_cfg=dict(backend='nccl'),
)

# set visualizer
visualizer = None

# set log level
log_level = 'INFO'

# load from which checkpoint
load_from = None

# whether to resume training from the loaded checkpoint
resume = False

# Defaults to use random seed and disable `deterministic`
randomness = dict(seed=None, deterministic=False)
```

**Comment by vansin** [comment]
```shell
pretrained_model_name_or_path = 'internlm-chat-7b-v1_1'
```

```shell
/xxxx/xxxxx/xxxxxx
```

**Comment by vansin** [comment]
please provide xtuner version

```shell
pip show xtuner
```

**Comment by maxchiron** [comment]
> please provide xtuner version
> 
> ```shell
> pip show xtuner
> ```

0.1.7

**Comment by maxchiron** [comment]
> ```shell
> pretrained_model_name_or_path = 'internlm-chat-7b-v1_1'
> ```
> 
> pealse try absolute path
> 
> ```shell
> /xxxx/xxxxx/internlm-chat-7b-v1_1
> ```

Same issue, unfortunately.

**Comment by vansin** [comment]
try install xtuner by source code

```shell
git clone xtuner
cd xtuner

pip install -e . 
```

**Comment by maxchiron** [comment]
> try install xtuner by source code
> 
> ```shell
> git clone xtuner
> cd xtuner
> 
> pip install -e . 
> ```

Same Issue. 😭

**Comment by LZHgrla** [comment]
Hi! @maxchiron  
Please exec below code to check the dataset format
```python
import tqdm
from modelscope.msdatasets import MsDataset

ds = MsDataset.load('damo/MSAgent-Bench') 
ds = ds['train'].to_hf_dataset()

for example in tqdm.tqdm(ds):
    eval(example['conversations']) 

```

**Comment by maxchiron** [comment]
Sorry for the interuption. It seems a problem invoked by my actions that "Creating soft link inside a soft link". The issue disappeared when I just use real folder and files. Sorry again.
