### ISSUE TITLE
训练好的pt模型转换为hf模型时报错ValueError: `data.device.type` must be 'cuda', detected cpu

### ISSUE THREAD

**Issue by rcejzibjks38** [InternLM/xtuner#215]
```bash
(lm) root@08f67918377b:~/project/xtuner# CUDA_VISIBLE_DEVICES=2 xtuner convert pth_to_hf configs/chatglm2_6b_qlora_lawyer_e3_copy.py work_dirs/chatglm2_6b_qlora_lawyer_e3_copy/epoch_2.pth work_dirs/chatglm2_6b_qlora_lawyer_e3_copy/epoch_2.pth/hf                            
[2023-11-10 01:56:10,696] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-10 01:56:16,505] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
quantization_config convert to <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:14<00:00,  2.08s/it]
Processing zero checkpoint 'work_dirs/chatglm2_6b_qlora_lawyer_e3_copy/epoch_2.pth'
Detected checkpoint of type zero stage 2, world_size: 4
Parsing checkpoint created by deepspeed==0.12.2
Reconstructed Frozen fp32 state dict with 199 params 3388311552 elements
Reconstructed fp32 state dict with 224 params 118587392 elements
Traceback (most recent call last):
  File "/root/project/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 105, in <module>
    main()
  File "/root/project/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 85, in main
    model.load_state_dict(state_dict, strict=False)
  File "/root/software/miniconda3/envs/lm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2138, in load_state_dict
    load(self, state_dict)
  File "/root/software/miniconda3/envs/lm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2126, in load
    load(child, child_state_dict, child_prefix)
  File "/root/software/miniconda3/envs/lm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2126, in load
    load(child, child_state_dict, child_prefix)
  File "/root/software/miniconda3/envs/lm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2126, in load
    load(child, child_state_dict, child_prefix)
  [Previous line repeated 7 more times]
  File "/root/software/miniconda3/envs/lm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2120, in load
    module._load_from_state_dict(
  File "/root/software/miniconda3/envs/lm/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 256, in _load_from_state_dict
    self.weight, state_dict = bnb.nn.Params4bit.from_state_dict(
  File "/root/software/miniconda3/envs/lm/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 169, in from_state_dict
    raise ValueError(f"`data.device.type` must be 'cuda', detected {data.device.type}")
ValueError: `data.device.type` must be 'cuda', detected cpu
```

**Comment by rcejzibjks38** [comment]
训练的命令是：
```bash
NPROC_PER_NODE=4 xtuner train configs/chatglm2_6b_qlora_lawyer_e3_copy.py --deepseed deepspeed_zero2
```

**Comment by rcejzibjks38** [comment]
这似乎是因为bitsandbytes包的一个if判断，
![image](https://github.com/InternLM/xtuner/assets/138190647/7cd275c3-e1c5-4664-a853-90e591cd0e89)
本项目是对bitsandbytes的版本有要求吗？

**Comment by rcejzibjks38** [comment]
问题解决，更新bitsanfbytes到最新版即可
![image](https://github.com/InternLM/xtuner/assets/138190647/792708d0-9deb-444d-bee2-02b6be363a5f)

**Comment by rcejzibjks38** [comment]
问题解决，更新bitsanfbytes到最新版即可
![image](https://github.com/InternLM/xtuner/assets/138190647/792708d0-9deb-444d-bee2-02b6be363a5f)
