### ISSUE TITLE
NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.

### ISSUE THREAD

**Issue by bencyq** [InternLM/xtuner#218]
报错信息显示无法从本地文件系统读取数据集，请问如何解决
错误信息：
(xtuner) [xxxxxxxx]$ xtuner check-custom-dataset chatglm3_6b_base_qlora_oasst1_e3_copy.py 
[2023-11-13 10:32:15,865] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-13 10:32:21,677] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Downloading and preparing dataset json/default to file:///public/home/u40817/.cache/huggingface/datasets/json/default-01e8ae4e85b60630/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4...
Downloading data files: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00, 11335.96it/s]
Extracting data files: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.58it/s]
Dataset json downloaded and prepared to file:///public/home/u40817/.cache/huggingface/datasets/json/default-01e8ae4e85b60630/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4. Subsequent calls will reuse this data.
Traceback (most recent call last):
  File "/public/home/u40817/cyq/xtuner/xtuner/tools/check_custom_dataset.py", line 76, in main
    dataset = BUILDER.build(dataset)
  File "/public/home/u40817/anaconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/public/home/u40817/anaconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/public/home/u40817/anaconda3/envs/xtuner/lib/python3.10/site-packages/datasets/load.py", line 1810, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
  File "/public/home/u40817/anaconda3/envs/xtuner/lib/python3.10/site-packages/datasets/builder.py", line 1128, in as_dataset
    raise NotImplementedError(f"Loading a dataset cached in a {type(self._fs).__name__} is not supported.")
NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/u40817/cyq/xtuner/xtuner/tools/check_custom_dataset.py", line 157, in <module>
    main()
  File "/public/home/u40817/cyq/xtuner/xtuner/tools/check_custom_dataset.py", line 78, in main
    raise RuntimeError(
RuntimeError: Unable to load the custom JSON file using `datasets.load_dataset`. Your data-related config is {'type': process_hf_dataset, 'dataset': {'type': load_dataset, 'path': 'json', 'data_files': {'train': '/public/home/u40817/cyq/dataset.json'}}, 'tokenizer': {'type': from_pretrained, 'pretrained_model_name_or_path': '/public/home/u40817/cyq/models/THUDM/chatglm3-6b', 'trust_remote_code': True, 'padding_side': 'left'}, 'max_length': 2048, 'dataset_map_fn': None, 'template_map_fn': {'type': template_map_fn_factory, 'template': default}, 'remove_unused_columns': True, 'shuffle_before_pack': True, 'pack_to_max_length': True}. Please refer to the official documentation on `load_dataset` (https://huggingface.co/docs/datasets/loading) for more details.

Json文件：
[{
    "conversation":[
        {
            "system": "",
            "input": "",
            "output": "xxxxxxx"
        }
    ]
},
{
    "conversation":[
        {
            "system": "",
            "input": "",
            "output": "xxxxxxx"
        }
    ]
}]

config文件信息：
data_path = '/xxxxx/dataset.json'
train_dataset = dict(
    type=process_hf_dataset,
    dataset=dict(type=load_dataset, 
    path='json', 
    data_files=dict(train=data_path)),
    tokenizer=tokenizer,
    max_length=max_length,
    dataset_map_fn=None,
    template_map_fn=dict(
        type=template_map_fn_factory, template=prompt_template),
    remove_unused_columns=True,
    shuffle_before_pack=True,
    pack_to_max_length=pack_to_max_length)

**Comment by LZHgrla** [comment]
https://github.com/InternLM/xtuner/issues/175#issuecomment-1782305062
