### ISSUE TITLE
chatglm3_6b full fine-tune to hf ckpt error

### ISSUE THREAD

**Issue by xiaohangguo** [InternLM/xtuner#220]
用chatglm3_6b 全量微调配置文件如下：
```
SYSTEM = 'xtuner.utils.SYSTEM_TEMPLATE.alpaca'
accumulative_counts = 16
alpaca_en = dict(
    dataset=dict(
        path='/public/home/lvshuhang/xtuner/train_data/ali_tianchi',
        type='datasets.load_dataset'),
    dataset_map_fn=None,
    max_length=2048,
    pack_to_max_length=True,
    remove_unused_columns=True,
    shuffle_before_pack=True,
    template_map_fn=dict(
        template='xtuner.utils.PROMPT_TEMPLATE.default',
        type='xtuner.dataset.map_fns.template_map_fn_factory'),
    tokenizer=dict(
        padding_side='left',
        pretrained_model_name_or_path=
        '/public/home/lvshuhang/model_space/workspace/THUDM_chatglm3-6b-base',
        trust_remote_code=True,
        type='transformers.AutoTokenizer.from_pretrained'),
    type='xtuner.dataset.process_hf_dataset')
alpaca_en_path = '/public/home/lvshuhang/xtuner/train_data/ali_tianchi'
batch_size = 4
betas = (
    0.9,
    0.999,
)
custom_hooks = [
    dict(
        tokenizer=dict(
            padding_side='left',
            pretrained_model_name_or_path=
            '/public/home/lvshuhang/model_space/workspace/THUDM_chatglm3-6b-base',
            trust_remote_code=True,
            type='transformers.AutoTokenizer.from_pretrained'),
        type='xtuner.engine.DatasetInfoHook'),
    dict(
        evaluation_inputs=[
            '怎样加热座椅？',
            'How do I heat the seats?',
        ],
        every_n_iters=500,
        prompt_template='xtuner.utils.PROMPT_TEMPLATE.default',
        system='xtuner.utils.SYSTEM_TEMPLATE.alpaca',
        tokenizer=dict(
            padding_side='left',
            pretrained_model_name_or_path=
            '/public/home/lvshuhang/model_space/workspace/THUDM_chatglm3-6b-base',
            trust_remote_code=True,
            type='transformers.AutoTokenizer.from_pretrained'),
        type='xtuner.engine.EvaluateChatHook'),
]
dataloader_num_workers = 0
default_hooks = dict(
    checkpoint=dict(interval=1, type='mmengine.hooks.CheckpointHook'),
    logger=dict(interval=10, type='mmengine.hooks.LoggerHook'),
    param_scheduler=dict(type='mmengine.hooks.ParamSchedulerHook'),
    sampler_seed=dict(type='mmengine.hooks.DistSamplerSeedHook'),
    timer=dict(type='mmengine.hooks.IterTimerHook'))
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
evaluation_freq = 500
evaluation_inputs = [
    '怎样加热座椅？',
    'How do I heat the seats?',
]
launcher = 'slurm'
load_from = None
log_level = 'INFO'
lr = 0.0002
max_epochs = 3
max_length = 2048
max_norm = 1
model = dict(
    llm=dict(
        pretrained_model_name_or_path=
        '/public/home/lvshuhang/model_space/workspace/THUDM_chatglm3-6b-base',
        torch_dtype='torch.float16',
        trust_remote_code=True,
        type='transformers.AutoModelForCausalLM.from_pretrained'),
    type='xtuner.model.SupervisedFinetune')
optim_type = 'bitsandbytes.optim.PagedAdamW32bit'
optim_wrapper = dict(
    optimizer=dict(
        betas=(
            0.9,
            0.999,
        ),
        lr=0.0002,
        type='bitsandbytes.optim.PagedAdamW32bit',
        weight_decay=0),
    type='DeepSpeedOptimWrapper')
pack_to_max_length = True
param_scheduler = dict(
    T_max=3,
    by_epoch=True,
    convert_to_iter_based=True,
    eta_min=2e-05,
    type='mmengine.optim.CosineAnnealingLR')
pretrained_model_name_or_path = '/public/home/lvshuhang/model_space/workspace/THUDM_chatglm3-6b-base'
prompt_template = 'xtuner.utils.PROMPT_TEMPLATE.default'
randomness = dict(deterministic=False, seed=None)
resume = False
runner_type = 'FlexibleRunner'
strategy = dict(
    config=
    '/public/home/lvshuhang/xtuner/xtuner/configs/deepspeed/deepspeed_zero3.json',
    gradient_accumulation_steps=16,
    gradient_clipping=1,
    train_micro_batch_size_per_gpu=4,
    type='DeepSpeedStrategy')
tokenizer = dict(
    padding_side='left',
    pretrained_model_name_or_path=
    '/public/home/lvshuhang/model_space/workspace/THUDM_chatglm3-6b-base',
    trust_remote_code=True,
    type='transformers.AutoTokenizer.from_pretrained')
train_cfg = dict(by_epoch=True, max_epochs=3, val_interval=1)
train_dataloader = dict(
    batch_size=4,
    collate_fn=dict(type='xtuner.dataset.collate_fns.default_collate_fn'),
    dataset=dict(
        dataset=dict(
            path='/public/home/lvshuhang/xtuner/train_data/ali_tianchi',
            type='datasets.load_dataset'),
        dataset_map_fn=None,
        max_length=2048,
        pack_to_max_length=True,
        remove_unused_columns=True,
        shuffle_before_pack=True,
        template_map_fn=dict(
            template='xtuner.utils.PROMPT_TEMPLATE.default',
            type='xtuner.dataset.map_fns.template_map_fn_factory'),
        tokenizer=dict(
            padding_side='left',
            pretrained_model_name_or_path=
            '/public/home/lvshuhang/model_space/workspace/THUDM_chatglm3-6b-base',
            trust_remote_code=True,
            type='transformers.AutoTokenizer.from_pretrained'),
        type='xtuner.dataset.process_hf_dataset'),
    num_workers=0,
    sampler=dict(shuffle=True, type='mmengine.dataset.DefaultSampler'))
visualizer = None
weight_decay = 0
work_dir = './work_dirs/chatglm3_6b_base_full_alpaca_e3'
```
用的 deepspeed zero3

然后得到了
![image](https://github.com/InternLM/xtuner/assets/72799392/0272fbc0-04d4-4e62-937e-ea50480fe5c8)
按理说应该是类似下面这样的：
![image](https://github.com/InternLM/xtuner/assets/72799392/cacceaa5-e694-448d-9968-8b5949062987)
不知道为什么好像自己已经转成了pt，但是又没有其他的东西，比如tokenizer json那些

然后尝试转hf 的ckpt，出了这个问题：
```
(xtuner) [lvshuhang@node61 chatglm3_6b_base_full_alpaca_e3]$ python zero_to_fp32.py ./ ./epoch_3.pth/pyt
orch_model.bin
[2023-11-13 20:11:07,724] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/public/home/lvshuhang/xtuner/work_dirs/chatglm3_6b_base_full_alpaca_e3/zero_to_fp32.py", line 587, in <module>
    convert_zero_checkpoint_to_fp32_state_dict(args.checkpoint_dir, args.output_file, tag=args.tag)
  File "/public/home/lvshuhang/xtuner/work_dirs/chatglm3_6b_base_full_alpaca_e3/zero_to_fp32.py", line 523, in convert_zero_checkpoint_to_fp32_state_dict
    state_dict = get_fp32_state_dict_from_zero_checkpoint(checkpoint_dir, tag)
  File "/public/home/lvshuhang/xtuner/work_dirs/chatglm3_6b_base_full_alpaca_e3/zero_to_fp32.py", line 502, in get_fp32_state_dict_from_zero_checkpoint
    raise ValueError(f"Unable to find 'latest' file at {latest_path}")
ValueError: Unable to find 'latest' file at ./latest
```

**Comment by xiaohangguo** [comment]
```
python zero_to_fp32.py ./ ./epoch_3.pth/pyt
orch_model.bin --tag epoch_3.pth
```
设置一下tag即可
