### ISSUE TITLE
TypeError: llama_attn_forward() got an unexpected keyword argument 'padding_mask' in <xtuner.engine.hooks.evaluate_chat_hook.EvaluateChatHook object at 0x7fecc4b82260>

### ISSUE THREAD

**Issue by peonutButter** [InternLM/xtuner#228]
cfg: llama2_7b_qlora_moss_sft_all_e1  

11/16 13:47:38 - mmengine - INFO - before_train in EvaluateChatHook.
Traceback (most recent call last):
  File "/opt/data/anaconda2-2020.2/envs/xtuner-env/lib/python3.10/site-packages/xtuner/tools/train.py", line 259, in <module>
    main()
  File "/opt/data/anaconda2-2020.2/envs/xtuner-env/lib/python3.10/site-packages/xtuner/tools/train.py", line 255, in main
    runner.train()
  File "/opt/data/anaconda2-2020.2/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/opt/data/anaconda2-2020.2/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/loops.py", line 93, in run
    self.runner.call_hook('before_train')
  File "/opt/data/anaconda2-2020.2/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1841, in call_hook
    raise TypeError(f'{e} in {hook}') from None
TypeError: llama_attn_forward() got an unexpected keyword argument 'padding_mask' in <xtuner.engine.hooks.evaluate_chat_hook.EvaluateChatHook object at 0x7fecc4b82260>

**Comment by LZHgrla** [comment]
#229 will solve this problem
