### ISSUE TITLE
can't muti gpu training

### ISSUE THREAD

**Issue by xiaohangguo** [InternLM/xtuner#238]
启动命令
```
deepspeed --hostfile /public/home/lvshuhang/LMFlow-main/configs/my_hostfile \
--include="10.110.3.61:2,3@10.110.3.62:2,3@10.110.3.65:0,1@10.110.3.66:0,1" \
--master_port=11000 \
xtuner/tools/train.py /public/home/lvshuhang/xtuner/xtuner/configs/llama/llama2_7b/wizard13b_ted_e1_wizard_system.py --launcher none --deepspeed /public/home/lvshuhang/xtuner/xtuner/configs/deepspeed/deepspeed_zero2.json
```

```
ic/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
10.110.3.66: frame #16: <unknown function> + 0x5498f30 (0x2b8393f72f30 in /public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
10.110.3.66: frame #17: <unknown function> + 0xb744ce (0x2b838e4ee4ce in /public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
10.110.3.66: frame #18: <unknown function> + 0x3bfdf0 (0x2b838dd39df0 in /public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
10.110.3.66: frame #19: <unknown function> + 0x1887e6 (0x55e36a7347e6 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #20: _PyObject_MakeTpCall + 0x37f (0x55e36a6f5b3f in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #21: <unknown function> + 0xd0485 (0x55e36a67c485 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #22: _PyEval_EvalFrameDefault + 0x13eb (0x55e36a77ca0b in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #23: <unknown function> + 0x1a579a (0x55e36a75179a in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #24: _PyFunction_Vectorcall + 0x117 (0x55e36a7522e7 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #25: _PyEval_EvalFrameDefault + 0x13eb (0x55e36a77ca0b in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #26: <unknown function> + 0x1a6f92 (0x55e36a752f92 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #27: _PyEval_EvalFrameDefault + 0x13eb (0x55e36a77ca0b in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #28: <unknown function> + 0x230ac8 (0x55e36a7dcac8 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #29: PyVectorcall_Call + 0x1ab (0x55e36a729d0b in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #30: _PyEval_EvalFrameDefault + 0x2290 (0x55e36a77d8b0 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #31: <unknown function> + 0x1a58f6 (0x55e36a7518f6 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #32: _PyFunction_Vectorcall + 0x117 (0x55e36a7522e7 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #33: _PyEval_EvalFrameDefault + 0x4910 (0x55e36a77ff30 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #34: <unknown function> + 0x1a6f92 (0x55e36a752f92 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #35: _PyEval_EvalFrameDefault + 0x13eb (0x55e36a77ca0b in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #36: <unknown function> + 0x1a7b23 (0x55e36a753b23 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #37: _PyEval_EvalFrameDefault + 0x13eb (0x55e36a77ca0b in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #38: <unknown function> + 0x1a7b23 (0x55e36a753b23 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #39: PyVectorcall_Call + 0x9c (0x55e36a729bfc in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #40: _PyEval_EvalFrameDefault + 0x2290 (0x55e36a77d8b0 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #41: <unknown function> + 0x1a6f92 (0x55e36a752f92 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #42: _PyEval_EvalFrameDefault + 0x13eb (0x55e36a77ca0b in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #43: _PyFunction_Vectorcall + 0x383 (0x55e36a752553 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #44: _PyEval_EvalFrameDefault + 0x868 (0x55e36a77be88 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #45: _PyFunction_Vectorcall + 0x383 (0x55e36a752553 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #46: <unknown function> + 0x1a70d2 (0x55e36a7530d2 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #47: PyVectorcall_Call + 0x1ab (0x55e36a729d0b in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #48: _PyEval_EvalFrameDefault + 0x2290 (0x55e36a77d8b0 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #49: <unknown function> + 0x1a579a (0x55e36a75179a in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #50: _PyFunction_Vectorcall + 0x117 (0x55e36a7522e7 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #51: _PyEval_EvalFrameDefault + 0x868 (0x55e36a77be88 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #52: _PyFunction_Vectorcall + 0x383 (0x55e36a752553 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #53: _PyEval_EvalFrameDefault + 0x868 (0x55e36a77be88 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #54: _PyFunction_Vectorcall + 0x383 (0x55e36a752553 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #55: _PyEval_EvalFrameDefault + 0x868 (0x55e36a77be88 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #56: _PyFunction_Vectorcall + 0x383 (0x55e36a752553 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #57: _PyEval_EvalFrameDefault + 0x868 (0x55e36a77be88 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #58: _PyFunction_Vectorcall + 0x383 (0x55e36a752553 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #59: _PyEval_EvalFrameDefault + 0x4b6 (0x55e36a77bad6 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #60: <unknown function> + 0x1a579a (0x55e36a75179a in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #61: _PyEval_EvalCodeWithName + 0x4b (0x55e36a75214b in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #62: PyEval_EvalCodeEx + 0x44 (0x55e36a752194 in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: frame #63: PyEval_EvalCode + 0x1c (0x55e36a7521bc in /public/home/lvshuhang/miniconda3/envs/xtuner/bin/python)
10.110.3.66: . This may indicate a possible application crash on rank 0 or a network set up issue.
10.110.3.66: [2023-11-21 14:31:55,242] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 6838
10.110.3.66: [2023-11-21 14:31:55,243] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 6839
10.110.3.66: [2023-11-21 14:31:56,142] [ERROR] [launch.py:321:sigkill_handler] ['/public/home/lvshuhang/miniconda3/envs/xtuner/bin/python', '-u', 'xtuner/tools/train.py', '--local_rank=1', '/public/home/lvshuhang/xtuner/xtuner/configs/llama/llama2_7b/wizard13b_ted_e1_wizard_system.py', '--launcher', 'none', '--deepspeed', '/public/home/lvshuhang/xtuner/xtuner/configs/deepspeed/deepspeed_zero2.json'] exits with return code = 1
pdsh@node61: 10.110.3.66: ssh exited with exit code 1
10.110.3.61: [2023-11-21 14:43:35,986] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 19619
10.110.3.61: [2023-11-21 14:43:35,988] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 19620
10.110.3.61: [2023-11-21 14:43:36,813] [ERROR] [launch.py:321:sigkill_handler] ['/public/home/lvshuhang/miniconda3/envs/xtuner/bin/python', '-u', 'xtuner/tools/train.py', '--local_rank=1', '/public/home/lvshuhang/xtuner/xtuner/configs/llama/llama2_7b/wizard13b_ted_e1_wizard_system.py', '--launcher', 'none', '--deepspeed', '/public/home/lvshuhang/xtuner/xtuner/configs/deepspeed/deepspeed_zero2.json'] exits with return code = -15
pdsh@node61: 10.110.3.61: ssh exited with exit code 241
```
资源占用状况是，两个gpu 一人一个进程，用了两个核，cpu占用是200% ，gpu利用率100%，这样会持续20多分钟，然后被杀掉。

第二种启动方式在80G显存下，13B模型直接爆显存，不知道为什么
`srun -p gpu --job-name=xtuner --nodes=2 --gres=gpu:2 --ntasks-per-node=2 --cpus-per-task=2 --mem=204800 xtuner train /public/home/lvshuhang/xtuner/xtuner/configs/llama/llama2_7b/wizard13b_ted_e1_wizard_system.py --launcher slurm --deepspeed /public/home/lvshuhang/xtuner/xtuner/configs/deepspeed/deepspeed_zero2.json
`

```
Found cached dataset json (/public/home/lvshuhang/.cache/huggingface/datasets/json/dataset-c15f55951d25777e/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|██████████| 1/1 [00:00<00:00, 37.51it/s]
Loading cached processed dataset at /public/home/lvshuhang/.cache/huggingface/datasets/json/dataset-c15f55951d25777e/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-d7eb2d2d45fc3e1e_*_of_00032.arrow
Loading cached processed dataset at /public/home/lvshuhang/.cache/huggingface/datasets/json/dataset-c15f55951d25777e/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-670e3fcaf0d1a755.arrow
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading cached processed dataset at /public/home/lvshuhang/.cache/huggingface/datasets/json/dataset-c15f55951d25777e/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-31735a1f8702bdc1_*_of_00032.arrow
11/21 14:52:11 - mmengine - WARNING - Dataset Dataset has no metainfo. ``dataset_meta`` in visualizer will be None.
Loading checkpoint shards: 100%|██████████| 3/3 [00:33<00:00, 11.01s/it]             
Loading checkpoint shards: 100%|██████████| 3/3 [00:33<00:00, 11.03s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:33<00:00, 11.03s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:33<00:00, 11.02s/it]
11/21 14:52:45 - mmengine - INFO - dispatch llama attn forward
11/21 14:52:45 - mmengine - WARNING - Due to the implementation of the PyTorch version of flash attention, even when the `output_attentions` flag is set to True, it is not possible to return the `attn_weights`.
[2023-11-21 14:53:19,848] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.12.3, git-hash=unknown, git-branch=unknown
Traceback (most recent call last):
  File "/public/home/lvshuhang/xtuner/xtuner/tools/train.py", line 267, in <module>
Traceback (most recent call last):
  File "/public/home/lvshuhang/xtuner/xtuner/tools/train.py", line 267, in <module>
    main()
    main()
  File "/public/home/lvshuhang/xtuner/xtuner/tools/train.py", line 263, in main
  File "/public/home/lvshuhang/xtuner/xtuner/tools/train.py", line 263, in main
    runner.train()
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/runner/_flexible_runner.py", line 1182, in train
    runner.train()
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/runner/_flexible_runner.py", line 1182, in train
    self.strategy.prepare(
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/_strategy/deepspeed.py", line 381, in prepare
    self.strategy.prepare(
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/_strategy/deepspeed.py", line 381, in prepare
    self.model = self._wrap_model(model)
    self.model = self._wrap_model(model)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/_strategy/deepspeed.py", line 396, in _wrap_model
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/_strategy/deepspeed.py", line 396, in _wrap_model
    engine, self.optim_wrapper.optimizer, *_ = deepspeed.initialize(
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine, self.optim_wrapper.optimizer, *_ = deepspeed.initialize(
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 262, in __init__
    engine = DeepSpeedEngine(args=args,
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 262, in __init__
    self._configure_distributed_model(model)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1084, in _configure_distributed_model
    self._configure_distributed_model(model)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1084, in _configure_distributed_model
    self.module.to(self.device)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 208, in to
    self.module.to(self.device)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 208, in to
    return super().to(*args, **kwargs)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return super().to(*args, **kwargs)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
    return self._apply(convert)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    param_applied = fn(param)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 136.00 MiB (GPU 1; 79.20 GiB total capacity; 1.24 GiB already allocated; 55.31 MiB free; 1.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 136.00 MiB (GPU 0; 79.20 GiB total capacity; 1.11 GiB already allocated; 43.31 MiB free; 1.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
^Csrun: interrupt (one more within 1 sec to abort)
srun: step:185.0 tasks 0-1: running
srun: step:185.0 tasks 2-3: exited
```
代码 是pull过远程的main代码，然后
打印了一下`xtuner --version`
`11/21 15:05:51 - mmengine - INFO - 0.1.9`

**Comment by LZHgrla** [comment]
1. 使用 deepspeed xxx 命令起的训练任务，在保存时确实会出现这个问题，目前暂未定位到问题原因，推测是mmengine的并行backend 与 deepspeed 不兼容。 现阶段比较稳妥的方式还是使用 slurm 起多节点训练。
2. 4张80GB的卡只能进行 7B 的全量微调，13B 的话确实会显存 OOM。可以尝试增加卡数或降低模型尺寸、数据 `max_length`

**Comment by xiaohangguo** [comment]
1.测试了一下`--launcher pytorch`以后确实就可以了
2.试了一下`max_length=1024` 13B是可以训练的
