### ISSUE TITLE
pytorch指定GPU后仍旧使用GPU0？

### ISSUE THREAD

**Issue by creegon** [InternLM/xtuner#245]
我已经试图通过：
CUDA_VISIBLE_DEVICES=1 xtuner train configs/internlm_7b_qlora_alpaca_internlm_assistant.py
来指定使用第二块显卡，但是运行中仍然报错说我第一块显卡显存不足？
我看了一篇类似的解决方案：https://blog.csdn.net/weixin_41519463/article/details/110561374
是不是因为在运行中，有些地方默认为pytorch的初始化分配到了GPU0？（或者其他相似的默认分配到了GPU0？）
感激不尽！

具体报错信息如下：

Traceback (most recent call last):
  File "/home/undergrad/internlm_home_workspace/xtuner/xtuner/tools/train.py", line 248, in <module>
    main()
  File "/home/undergrad/internlm_home_workspace/xtuner/xtuner/tools/train.py", line 244, in main
    runner.train()
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 346, in _run_forward
    results = self(**data, mode=mode)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/undergrad/internlm_home_workspace/xtuner/xtuner/model/sft.py", line 82, in forward
    return self.compute_loss(data, data_samples)
  File "/home/undergrad/internlm_home_workspace/xtuner/xtuner/model/sft.py", line 102, in compute_loss
    outputs = self.llm(**data)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/peft/peft_model.py", line 918, in forward
    return self.base_model(
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/sxlab/.cache/huggingface/modules/transformers_modules/internlm-chat-7b/modeling_internlm.py", line 705, in forward
    logits = self.lm_head(hidden_states)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1008.00 MiB. GPU 0 has a total capacty of 47.53 GiB of which 453.06 MiB is free. Process 2800118 has 25.31 GiB memory in use. Process 3657303 has 2.66 GiB memory in use. Including non-PyTorch memory, this process has 19.08 GiB memory in use. Of the allocated memory 17.96 GiB is allocated by PyTorch, and 823.75 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by LZHgrla** [comment]
@creegon 
CUDA_VISIBLE_DEVICES=1 设置后，对于PyTorch程序而言它只能识别到1张卡，即你的第二张卡。
也正是因为只能识别到1张卡，所以该张卡的编号为 GPU 0，所以并没有问题。

通过报错发现该张卡上有其他程序占用了大量显存，可以等卡空了再尝试。
