### ISSUE TITLE
启动时加入visualizer后报错？

### ISSUE THREAD

**Issue by creegon** [InternLM/xtuner#246]
我在启动脚本里面添加了：
visualizer = dict(
    type=Visualizer, 
    vis_backends=[dict(type=WandbVisBackend)]
)
（原先是visualizer = None）

结果报错：TypeError: Object of type module is not JSON serializable（原先是没问题的）

完整报错：
Traceback (most recent call last):
  File "/home/undergrad/lh/internlm_home_workspace/xtuner/xtuner/tools/train.py", line 248, in <module>
    main()
  File "/home/undergrad/lh/internlm_home_workspace/xtuner/xtuner/tools/train.py", line 237, in main
    runner = Runner.from_cfg(cfg)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/mmengine/runner/runner.py", line 418, in __init__
    self.visualizer.add_config(self.cfg)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/mmengine/dist/utils.py", line 412, in wrapper
    return func(*args, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/mmengine/visualization/visualizer.py", line 1071, in add_config
    vis_backend.add_config(config, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/mmengine/visualization/vis_backend.py", line 60, in wrapper
    return old_func(obj, *args, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/mmengine/visualization/vis_backend.py", line 440, in add_config
    self._wandb.config.update(
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 186, in update
    self._callback(data=sanitized)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1344, in _config_callback
    self._backend.interface.publish_config(key=key, val=val, data=data)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 167, in publish_config
    cfg = self._make_config(data=data, key=key, val=val)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 122, in _make_config
    update.value_json = json_dumps_safer(json_friendly(v)[0])
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/wandb/util.py", line 828, in json_dumps_safer
    return dumps(obj, cls=WandBJSONEncoder, **kwargs)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages/wandb/util.py", line 779, in default
    return json.JSONEncoder.default(self, obj)
  File "/home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type module is not JSON serializable

**Comment by creegon** [comment]
@LZHgrla 
版本如下：
Name: mmengine
Version: 0.9.0
Summary: Engine of OpenMMLab projects
Home-page: https://github.com/open-mmlab/mmengine
Author: MMEngine Authors
Author-email: openmmlab@gmail.com
License: UNKNOWN
Location: /home/sxlab/miniconda3/envs/xtuner_lh/lib/python3.10/site-packages
Requires: addict, matplotlib, numpy, opencv-python, pyyaml, rich, termcolor, yapf
Required-by: lmdeploy, xtuner
---
Name: wandb
Version: 0.16.0
Summary: A CLI and library for interacting with the Weights & Biases API.
Home-page:
Author:
Author-email: Weights & Biases <support@wandb.com>

然后这个issue里面的解决方案：It seems that this bug is caused by dumping a lazy config to json.
指的是什么。。感激不尽！

**Comment by LZHgrla** [comment]
@creegon 
这个bug在 mmengine 0.9.1 中修复了，请尝试更新 mmengine 版本
```
pip install -U mmengine
```
