### ISSUE TITLE
CUDA OutOfMemoryError

### ISSUE THREAD

**Issue by donaldxu** [InternLM/xtuner#255]
Nvidia Tesla T4 8G，使用xtuner train baichuan2_7b_chat_qlora_alpaca_zh_e3 --deepspeed deepspeed_zero2 训练，报错如下
12/01 18:23:36 - mmengine - INFO - dispatch baichuan2-13B attn forward
Traceback (most recent call last):
  File "/data/workspace/xtuner/xtuner/tools/train.py", line 268, in <module>
    main()
  File "/data/workspace/xtuner/xtuner/tools/train.py", line 264, in main
    runner.train()
  File "/home/tensorflow/anaconda3/lib/python3.8/site-packages/mmengine/runner/_flexible_runner.py", line 1181, in train
    self.strategy.prepare(
  File "/home/tensorflow/anaconda3/lib/python3.8/site-packages/mmengine/_strategy/deepspeed.py", line 376, in prepare
    model = self.build_model(model)
  File "/home/tensorflow/anaconda3/lib/python3.8/site-packages/mmengine/_strategy/base.py", line 306, in build_model
    model = MODELS.build(model)
  File "/home/tensorflow/anaconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/tensorflow/anaconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/tensorflow/anaconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/data/workspace/xtuner/xtuner/model/sft.py", line 51, in __init__
    self._prepare_for_lora(peft_model, use_activation_checkpointing)
  File "/data/workspace/xtuner/xtuner/model/sft.py", line 58, in _prepare_for_lora
    self.llm = prepare_model_for_kbit_training(
  File "/home/tensorflow/anaconda3/lib/python3.8/site-packages/[peft-0.6.3.dev0-py3.8.egg/peft/utils/other.py](http://peft-0.6.3.dev0-py3.8.egg/peft/utils/other.py)", line 98, in prepare_model_for_kbit_training
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.92 GiB. GPU 0 has a total capacty of 7.43 GiB of which 1.20 GiB is free. Including non-PyTorch memory, this process has 6.23 GiB memory in use. Of the allocated memory 6.02 GiB is allocated by PyTorch, and 95.80 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by LZHgrla** [comment]
@donaldxu 
1. max_length 设置为 512，可以直接测试 `baichuan2_7b_chat_qlora_oasst1_512_e3`
2. `GPU 0 has a total capacty of 7.43 GiB.....` 7.43 GB 有可能是不够的，至少需要 ~8000 MB。另外，正常的 T4 应该是 16GB？

**Comment by donaldxu** [comment]
不好意思 搞错了 是P4

Zhihao Lin ***@***.***>于2023年12月1日 周五18:28写道：

**Comment by pppppM** [comment]
可能有两个问题：
- 没有修改 config 中的 max_length 为 512
- HuggingFace Cache 中的 Checkpoint 有问题



对于问题 1，如果不想改 config，可以直接使用 baichuan2_7b_chat_qlora_oasst1_512_e3 这个 config
oasst1_512 指使用 oasst1 这个数据集，数据集最大长度是 512
```
xtuner train baichuan2_7b_chat_qlora_alpaca_zh_e3 --deepspeed deepspeed_zero2
```

对于问题 2，请检查你本地 Checkpoint 文件夹中的 modeling_baichuan.py
百川2 7B 的代码中，Attention 模块的类名是 `Attention`
https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat/blob/main/modeling_baichuan.py#L172
而在 13B 模型的代码中，Attention 模块的类名是 `BaichuanAttention`
https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/blob/main/modeling_baichuan.py#L110

我们是根据 Attention 模块的类名来进行 dispatch 的，log 中出现了 dispatch baichuan2-13b, 说明加载的模型可能有些问题
