### ISSUE TITLE
基于多卡训练后，转换模型时报错

### ISSUE THREAD

**Issue by kaoyansoft123** [InternLM/xtuner#258]
在执行完多卡训练后，执行导出转换模型脚本时：xtuner convert pth_to_hf ${CONFIG_NAME_OR_PATH} ${PTH} ${SAVE_PATH}
报错如下：
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
        Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
[2023-12-06 10:28:49,410] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
quantization_config convert to <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:24<00:00,  8.28s/it]
12/06 10:29:19 - mmengine - INFO - dispatch baichuan2 NormHead forward
12/06 10:29:19 - mmengine - INFO - dispatch baichuan2-7B attn forward
12/06 10:29:19 - mmengine - WARNING - Due to the implementation of the PyTorch version of flash attention, even when the `output_attentions` flag is set to True, it is not possible to return the `attn_weights`.
12/06 10:29:19 - mmengine - INFO - dispatch baichuan2-13B attn forward
Processing zero checkpoint 'work_dirs/baichuan2_13b_chat_qlora_drilling_pt/epoch_280.pth'
Traceback (most recent call last):
  File "/mnt/bigdata/chatglm2/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 113, in <module>
    main()
  File "/mnt/bigdata/chatglm2/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 92, in main
    state_dict = guess_load_checkpoint(args.pth_model)
  File "/mnt/bigdata/chatglm2/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 68, in guess_load_checkpoint
    state_dict = get_fp32_state_dict_from_zero_checkpoint(
  File "/mnt/bigdata/chatglm2/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/deepspeed/utils/zero_to_fp32.py", line 509, in get_fp32_state_dict_from_zero_checkpoint
    return _get_fp32_state_dict_from_zero_checkpoint(ds_checkpoint_dir)
  File "/mnt/bigdata/chatglm2/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/deepspeed/utils/zero_to_fp32.py", line 205, in _get_fp32_state_dict_from_zero_checkpoint
    zero_stage, world_size, fp32_flat_groups = parse_optim_states(optim_files, ds_checkpoint_dir)
  File "/mnt/bigdata/chatglm2/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/deepspeed/utils/zero_to_fp32.py", line 165, in parse_optim_states
    raise ValueError(
ValueError: Expected 3 of '*_optim_states.pt' under 'work_dirs/baichuan2_13b_chat_qlora_drilling_pt/epoch_280.pth' but found 1 files. Possibly due to an overwrite of an old checkpoint, or a checkpoint didn't get saved by one or more processes.

**Comment by pppppM** [comment]
work_dir 的目录结构需要贴一下

**Comment by kaoyansoft123** [comment]
@pppppM 解决了。需要手动把各节点的权重文件copy到主节点中。目前此脚本还不能实现自动获取所有节点的权重文件。

**Comment by LZHgrla** [comment]
是多“机”训练吗？
