### ISSUE TITLE
KeyError: 'instruction_zh'

### ISSUE THREAD

**Issue by Zengfanxu1111** [InternLM/xtuner#270]
error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\xtuner\tools\train.py", line 268, in <module>
    main()
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\xtuner\tools\train.py", line 264, in main
    runner.train()
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\mmengine\runner\runner.py", line 1728, in train
    self._train_loop = self.build_train_loop(
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\mmengine\runner\runner.py", line 1527, in build_train_loop
    loop = EpochBasedTrainLoop(
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\mmengine\runner\loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\mmengine\runner\base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\mmengine\runner\runner.py", line 1370, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\xtuner\dataset\huggingface.py", line 136, in process_hf_dataset
    return process(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\xtuner\dataset\huggingface.py", line 80, in process
    dataset = dataset.map(dataset_map_fn, num_proc=map_num_proc)
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\datasets\arrow_dataset.py", line 591, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\datasets\arrow_dataset.py", line 556, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\datasets\arrow_dataset.py", line 3181, in map
    for rank, done, content in iflatmap_unordered(
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\datasets\utils\py_utils.py", line 1417, in iflatmap_unordered
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\datasets\utils\py_utils.py", line 1417, in <listcomp>
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\multiprocess\pool.py", line 774, in get
    raise self._value
KeyError: 'instruction_zh'

**Comment by LZHgrla** [comment]
@Zengfanxu1111 
Please post your config and the command~

**Comment by Zengfanxu1111** [comment]
this is my command:
xtuner train chatglm3_6b_base_qlora_alpaca_zh_e3_copy.py --work-dir finetuend_model
==============================================================
this is config from chatglm3_6b_base_qlora_alpaca_zh_e3_copy.py:
      # Model
pretrained_model_name_or_path = 'chatglm-6b-base/models--THUDM--chatglm3-6b-base/snapshots/f91a1de587fdc692073367198e65369669a0b49d'

# Data
alpaca_zh_path = './data'
prompt_template = PROMPT_TEMPLATE.chatglm3
max_length = 2048
pack_to_max_length = True

# Scheduler & Optimizer
batch_size = 1  # per_device
accumulative_counts = 16
dataloader_num_workers = 0
max_epochs = 3
optim_type = PagedAdamW32bit
lr = 2e-4
betas = (0.9, 0.999)
weight_decay = 0
max_norm = 1  # grad clip

# Evaluate the generation performance during the training
evaluation_freq = 500
SYSTEM = SYSTEM_TEMPLATE.alpaca
evaluation_inputs = [
    '请给我一些医疗建议', 'Please give me some medical suggestions'
]
I copied code by <xtuner copy-cfg chatglm3_6b_base_qlora_alpaca_zh_e3  .>,

**Comment by LZHgrla** [comment]
@Zengfanxu1111 
Is `./data` downloaded from `silk-road/alpaca-data-gpt4-chinese`?

**Comment by Zengfanxu1111** [comment]
No,I make it by myself like this:
    [
    {
        "conversation": [
            {
                "system": "你是一个医疗专家。请回答我下面的问题。",
                "input": "病情描述发病时间、主要症状、症状变化等）：经常腰疼，双腿无力，没有精神，手淫频繁，射精太快，这是肾虚吗？",
                "output": "这种情况可能是由于手淫过度，导致的肾精不足，肾阴亏虚的问题建议使用中药治疗，常用的药物有六味地黄汤，左归丸等，平时注意休息，尽量戒除手淫"
            }
        ]
    },
    {
        "conversation": [
            {
                "system": "你是一个医疗专家。请回答我下面的问题。",
                "input": "颈3/4,4/5,5/6,6/7椎肩盘突出，脊髓受压变形，腰椎肩盘突出，相应水平黄韧带肥厚，下腰段椎管狭窄。，下腿无力，走路不稳，无，怎么治疗",
                "output": "您好！建议您可以到正规医院采用微创针刀治疗，效果不错。"
            }
        ]
    },
    {
        "conversation": [
            {
                "system": "你是一个医疗专家。请回答我下面的问题。",
                "input": "往裤子里滴尿是怎么回事，吃点什么药",
                "output": "你好，您的情况主要考虑是前列腺炎的可能，主要症状是尿后滴白，建议您去医院做下检查，确诊疾病，对症治疗，平时注意饮食，合理休息"
            }
        ]
    }
]

**Comment by LZHgrla** [comment]
Cool! The dataset has been mapped manually. Now, please set `dataset_map_fn=None` in your config.

Once that's done, everything should operate as expected!

**Comment by Zengfanxu1111** [comment]
It worked! Thank you very much!
