### ISSUE TITLE
使用zeor2_offloard多卡训练时报错

### ISSUE THREAD

**Issue by kaoyansoft123** [InternLM/xtuner#271]
Traceback (most recent call last):
  File "/home/jovyan/xtuner/xtuner/tools/train.py", line 268, in <module>
    main()
  File "/home/jovyan/xtuner/xtuner/tools/train.py", line 264, in main
    runner.train()
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1182, in train
    self.strategy.prepare(
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 381, in prepare
    self.model = self._wrap_model(model)
  File "/home/jovyan/xtuner/xtuner/engine/_strategy/deepspeed.py", line 15, in _wrap_model
    wrapper = super()._wrap_model(model)
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 396, in _wrap_model
    engine, self.optim_wrapper.optimizer, *_ = deepspeed.initialize(
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 304, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1222, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1483, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 510, in __init__
    self.initialize_optimizer_states()
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 645, in initialize_optimizer_states
    self.optimizer.step()
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 269, in step
    self.update_step(group, p, gindex, pindex)
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 469, in update_step
    F.optimizer_update_32bit(
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1218, in optimizer_update_32bit
    is_on_gpu([g, p, state1, state2, unorm_vec])
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/functional.py", line 391, in is_on_gpu
    raise TypeError(f'All input tensors need to be on the same GPU, but found some tensors to not be on a GPU:\n {[(t.shape, t.device) for t in tensors]}')
  File "/opt/conda/envs/xtuner/lib/python3.10/site-packages/bitsandbytes/functional.py", line 391, in <listcomp>
    raise TypeError(f'All input tensors need to be on the same GPU, but found some tensors to not be on a GPU:\n {[(t.shape, t.device) for t in tensors]}')
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by LZHgrla** [comment]
https://github.com/InternLM/xtuner/issues/236

bitsandbytes的optimizer不支持offloading

**Comment by kaoyansoft123** [comment]
@LZHgrla 哪些优化器支持啊

**Comment by LZHgrla** [comment]
@kaoyansoft123  在 torch.optim.AdamW 测试是没问题的，其他 torch optimizer 应该也是ok的
