### ISSUE TITLE
Use Lora for mixtral

### ISSUE THREAD

**Issue by jjjkkyz** [InternLM/xtuner#286]
As I need use Lora with mixtral 8x7b, I need to modify config file. But simply remove ```quantization_config``` in ```mixtral_8x7b_instruct_qlora_oasst1_e3.py``` report an error.

```
[2023-12-28 08:24:09,455] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 953662 closing signal SIGTERM
[2023-12-28 08:24:09,456] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 953663 closing signal SIGTERM
[2023-12-28 08:24:09,456] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 953664 closing signal SIGTERM
[2023-12-28 08:24:09,456] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 953665 closing signal SIGTERM
[2023-12-28 08:24:09,456] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 953666 closing signal SIGTERM
[2023-12-28 08:24:09,456] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 953667 closing signal SIGTERM
[2023-12-28 08:24:09,457] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 953669 closing signal SIGTERM
[2023-12-28 08:24:21,550] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 6 (pid: 953668) of binary: /data/users/chenxh/envs/xtuner/bin/python
Traceback (most recent call last):
  File "/data/users/chenxh/envs/xtuner/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0', 'console_scripts', 'torchrun')())
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/xtuner/tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-28_08:24:09
  host      : ip-172-31-38-5.ec2.internal
  rank      : 6 (local_rank: 6)
  exitcode  : -9 (pid: 953668)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 953668
============================================================

```

So, what should I do to use lora instead of Qlora in mixtral8x7b?

**Comment by LZHgrla** [comment]
It seem that this issue is caused by OOM in gpu or ram.

Try to use `--deepspeed deepspeed_zero3` for lora instead of zero2.

Also, you can post the training command and the gpus/ ram memory you used， so that I can try to reproduce and solve it.

**Comment by jjjkkyz** [comment]
Thanks, it works for deepspeed_zero3.
I train model with ``` NPROC_PER_NODE=8 xtuner train ${config_file} --deepspeed deepspeed_zero2``` in 8 A100-SXM4-80GB.
I have no root permision, so I don't know which ram is used.

**Comment by LZHgrla** [comment]
Great!
zero2 doesn't split the model, so it will lead to OOM on GPU
