### ISSUE TITLE
Saving checkpoint error when full finetune mixtral 8x7b

### ISSUE THREAD

**Issue by jjjkkyz** [InternLM/xtuner#315]
I am saving checkpoint in a shared dict(/data01/models/psd/xtuner_mixtral8x7b_full/) of two machine(each with 8 A100 80G).
And got a error log below:
```
01/14 06:58:51 - mmengine - INFO - Epoch(train) [1][260/276]  lr: 1.6281e-05  eta: 5:41:56  time: 35.9479  data_time: 0.0071  memory: 64895  loss: 0.1988
01/14 07:04:54 - mmengine - INFO - Epoch(train) [1][270/276]  lr: 1.5982e-05  eta: 5:35:59  time: 36.3233  data_time: 0.0071  memory: 64895  loss: 0.1539
[2024-01-14 07:06:08,350] [WARNING] [stage3.py:1991:step] 20 pytorch allocator cache flushes since last step. this happens when there is high memory pressure and is detrimental to performance. if this is happening frequently consider adjusting settings to reduce memory consumption. If you are unable to make the cache flushes go away consider adding get_accelerator().empty_cache() calls in your training loop to ensure that all ranks flush their caches at the same time
01/14 07:08:35 - mmengine - INFO - Exp name: mixtral_8x7b_instruct_full_20240114_041454
01/14 07:08:35 - mmengine - INFO - Saving checkpoint at 1 epochs
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
To disable this warning, you can either:
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable 	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable 	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISMTOKENIZERS_PARALLELISMTOKENIZERS_PARALLELISM=(true | false)
=(true | false)
=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
[2024-01-14 07:08:35,428] [INFO] [logging.py:96:log_dist] [Rank 0] [Torch] Checkpoint epoch_1.pth is about to be saved!
/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
[2024-01-14 07:08:35,448] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_4_mp_rank_00_model_states.pt...
[2024-01-14 07:08:35,448] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_5_mp_rank_00_model_states.pt...
[2024-01-14 07:08:35,448] [INFO] [logging.py:96:log_dist] [Rank 1] Saving model checkpoint: /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_1_mp_rank_00_model_states.pt
[2024-01-14 07:08:35,448] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_1_mp_rank_00_model_states.pt...
[2024-01-14 07:08:35,448] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_3_mp_rank_00_model_states.pt...
[2024-01-14 07:08:35,451] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_7_mp_rank_00_model_states.pt...
[2024-01-14 07:08:35,451] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_2_mp_rank_00_model_states.pt...
[2024-01-14 07:08:35,451] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_6_mp_rank_00_model_states.pt...
[2024-01-14 07:08:35,452] [INFO] [logging.py:96:log_dist] [Rank 0] Saving model checkpoint: /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_0_mp_rank_00_model_states.pt
[2024-01-14 07:08:35,452] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_0_mp_rank_00_model_states.pt...
[2024-01-14 07:08:35,493] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_4_mp_rank_00_model_states.pt.
[2024-01-14 07:08:35,494] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_5_mp_rank_00_model_states.pt.
[2024-01-14 07:08:35,494] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_3_mp_rank_00_model_states.pt.
[2024-01-14 07:08:35,494] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_1_mp_rank_00_model_states.pt.
[2024-01-14 07:08:35,497] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_7_mp_rank_00_model_states.pt.
[2024-01-14 07:08:35,498] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_6_mp_rank_00_model_states.pt.
[2024-01-14 07:08:35,498] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_0_mp_rank_00_model_states.pt.
[2024-01-14 07:08:35,499] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/zero_pp_rank_2_mp_rank_00_model_states.pt.
[2024-01-14 07:08:35,505] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/bf16_zero_pp_rank_0_mp_rank_00_optim_states.pt...
[2024-01-14 07:08:35,505] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/bf16_zero_pp_rank_4_mp_rank_00_optim_states.pt...
[2024-01-14 07:08:35,505] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/bf16_zero_pp_rank_1_mp_rank_00_optim_states.pt...
[2024-01-14 07:08:35,505] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/bf16_zero_pp_rank_2_mp_rank_00_optim_states.pt...
[2024-01-14 07:08:35,505] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/bf16_zero_pp_rank_7_mp_rank_00_optim_states.pt...
[2024-01-14 07:08:35,505] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/bf16_zero_pp_rank_3_mp_rank_00_optim_states.pt...
[2024-01-14 07:08:35,505] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/bf16_zero_pp_rank_5_mp_rank_00_optim_states.pt...
[2024-01-14 07:08:35,505] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/bf16_zero_pp_rank_6_mp_rank_00_optim_states.pt...
Traceback (most recent call last):
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 619, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 853, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at inline_container.cc:588] . PytorchStreamWriter failed writing file data/10: file write failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/xtuner/tools/train.py", line 277, in <module>
    main()
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/xtuner/tools/train.py", line 273, in main
    runner.train()
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/mmengine/runner/_flexible_runner.py", line 1200, in train
    model = self.train_loop.run()  # type: ignore
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/mmengine/runner/loops.py", line 114, in run_epoch
    self.runner.call_hook('after_train_epoch')
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/mmengine/runner/_flexible_runner.py", line 1271, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/mmengine/hooks/checkpoint_hook.py", line 345, in after_train_epoch
    self._save_checkpoint(runner)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/mmengine/hooks/checkpoint_hook.py", line 476, in _save_checkpoint
    self._save_checkpoint_with_step(runner, step, meta=meta)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/mmengine/hooks/checkpoint_hook.py", line 443, in _save_checkpoint_with_step
    runner.save_checkpoint(
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/mmengine/runner/_flexible_runner.py", line 1613, in save_checkpoint
    self.strategy.save_checkpoint(
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/mmengine/_strategy/deepspeed.py", line 540, in save_checkpoint
    self.model.save_checkpoint(
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 3082, in save_checkpoint
    self._save_zero_checkpoint(save_dir, tag)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 3426, in _save_zero_checkpoint
    self.checkpoint_engine.save(zero_sd, zero_checkpoint_name)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/deepspeed/runtime/checkpoint_engine/torch_checkpoint_engine.py", line 22, in save
    torch.save(state_dict, path)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 620, in save
    return
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 466, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:424] . unexpected pos 4009081472 vs 4009081360
ip-172-31-37-82:2353015:2355048 [6] NCCL INFO [Service thread] Connection closed by localRank 3
ip-172-31-37-82:2353013:2355051 [4] NCCL INFO [Service thread] Connection closed by localRank 3
ip-172-31-37-82:2353011:2355053 [2] NCCL INFO [Service thread] Connection closed by localRank 3
ip-172-31-37-82:2353009:2355054 [0] NCCL INFO [Service thread] Connection closed by localRank 3
ip-172-31-37-82:2353015:2353111 [6] NCCL INFO [Service thread] Connection closed by localRank 3
ip-172-31-37-82:2353013:2353113 [4] NCCL INFO [Service thread] Connection closed by localRank 3
ip-172-31-37-82:2353009:2353107 [0] NCCL INFO [Service thread] Connection closed by localRank 3
ip-172-31-37-82:2353011:2353114 [2] NCCL INFO [Service thread] Connection closed by localRank 3
[2024-01-14 07:09:25,181] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2353009 closing signal SIGTERM
[2024-01-14 07:09:25,182] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2353010 closing signal SIGTERM
[2024-01-14 07:09:25,182] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2353011 closing signal SIGTERM
[2024-01-14 07:09:25,182] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2353013 closing signal SIGTERM
[2024-01-14 07:09:25,182] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2353014 closing signal SIGTERM
[2024-01-14 07:09:25,182] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2353015 closing signal SIGTERM
[2024-01-14 07:09:25,182] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2353016 closing signal SIGTERM
ip-172-31-37-82:2353015:2355048 [6] NCCL INFO [Service thread] Connection closed by localRank 4
ip-172-31-37-82:2353009:2355054 [0] NCCL INFO [Service thread] Connection closed by localRank 4
ip-172-31-37-82:2353011:2355053 [2] NCCL INFO [Service thread] Connection closed by localRank 4
ip-172-31-37-82:2353015:2353111 [6] NCCL INFO [Service thread] Connection closed by localRank 4
ip-172-31-37-82:2353011:2353114 [2] NCCL INFO [Service thread] Connection closed by localRank 4
ip-172-31-37-82:2353009:2353107 [0] NCCL INFO [Service thread] Connection closed by localRank 4
ip-172-31-37-82:2353015:2355048 [6] NCCL INFO [Service thread] Connection closed by localRank 5
ip-172-31-37-82:2353011:2355053 [2] NCCL INFO [Service thread] Connection closed by localRank 5
ip-172-31-37-82:2353009:2355054 [0] NCCL INFO [Service thread] Connection closed by localRank 5
ip-172-31-37-82:2353015:2353111 [6] NCCL INFO [Service thread] Connection closed by localRank 5
ip-172-31-37-82:2353011:2353114 [2] NCCL INFO [Service thread] Connection closed by localRank 5
ip-172-31-37-82:2353009:2353107 [0] NCCL INFO [Service thread] Connection closed by localRank 5
[2024-01-14 07:09:32,705] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 3 (pid: 2353012) of binary: /data/users/chenxh/envs/xtuner/bin/python
Traceback (most recent call last):
  File "/data/users/chenxh/envs/xtuner/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0', 'console_scripts', 'torchrun')())
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/xtuner/tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-14_07:09:25
  host      : ip-172-31-37-82.ec2.internal
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 2353012)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

Corresponding log in child node machin is :
```
[2024-01-14 07:08:35,505] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/bf16_zero_pp_rank_15_mp_rank_00_optim_states.pt...
[2024-01-14 07:08:35,505] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/bf16_zero_pp_rank_12_mp_rank_00_optim_states.pt...
[2024-01-14 07:08:35,505] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/bf16_zero_pp_rank_10_mp_rank_00_optim_states.pt...
[2024-01-14 07:08:35,505] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /data01/models/psd/xtuner_mixtral8x7b_full/epoch_1.pth/bf16_zero_pp_rank_13_mp_rank_00_optim_states.pt...
Traceback (most recent call last):
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 619, in save
Traceback (most recent call last):
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 619, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 853, in _save
Traceback (most recent call last):
Traceback (most recent call last):
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 619, in save
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 619, in save
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 619, in save
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 619, in save
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 619, in save
Connection websocket closedle, pickle_module, pickle_protocol, _disable_byteorder_record)
  File "/data/users/chenxh/envs/xtuner/lib/python3.9/site-packages/torch/serialization.py", line 853, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at inline_container.cc:588] . PytorchStreamWriter failed writing file data/1: file write failed

During handling of the above exception, another exception occurred:

```

**Comment by jjjkkyz** [comment]
File in /data01/models/psd/xtuner_mixtral8x7b_full/epoech_01.pth is:
![image](https://github.com/InternLM/xtuner/assets/25861711/fccb839a-5d7e-4f65-8e39-a35fae9afb9a)

**Comment by LZHgrla** [comment]
Please double-check that whether the disk is full
