### ISSUE TITLE
xtuner 0.1.13dev版本 FineTune报错：command error: 'libGL.so.1: cannot open shared object file: No such file or directory'!

### ISSUE THREAD

**Issue by zhanghui-china** [InternLM/xtuner#330]
WSL上全新conda环境：
conda create -n xtunernew python=3.10 -y
conda activate xtunernew 
mkdir xtunernew && cd xtunernew
git clone https://github.com/InternLM/xtuner
cd xtuner
pip install -e '.[all]'

xtuner version
<img width="428" alt="e86ee0aebd8475ac2eefe063cc26fe8" src="https://github.com/InternLM/xtuner/assets/63148804/5f74e8bf-ad33-4ec3-a217-b79d32ef73fc">

mkdir ~/shishen2 && cd ~/shishen2
xtuner copy-cfg internlm2_chat_7b_qlora_oasst1_e3 .
xtuner train  ./internlm2_chat_7b_qlora_oasst1_e3_copy.py --deepspeed deepspeed_zero2
报错如下：
<img width="1004" alt="bc79ef4e0159148d410a8fe2000d940" src="https://github.com/InternLM/xtuner/assets/63148804/f735b1f1-4a15-4743-9ed1-05b0e4c113b5">

<img width="1009" alt="641976b0cabe3aa3d61d675bc2c40bd" src="https://github.com/InternLM/xtuner/assets/63148804/8eb1d52a-7085-4cfb-a029-600890e93f35">

**Comment by LZHgrla** [comment]
```
cd xtuner
python xtuner/tools/train.py ./internlm2_chat_7b_qlora_oasst1_e3_copy.py --deepspeed deepspeed_zero2
```
尝试执行该命令，确定一下具体的报错行号

**Comment by zhanghui-china** [comment]
(xtunernew) zhanghui@zhanghui:~/xtunernew/xtuner$ python xtuner/tools/train.py ./internlm2_chat_7b_qlora_oasst1_e3_copy.py --deepspeed deepspeed_zero2
[2024-01-20 12:37:45,906] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/zhanghui/xtunernew/xtuner/xtuner/tools/train.py", line 14, in <module>
    from mmengine.runner import Runner
  File "/home/zhanghui/anaconda3/envs/xtunernew/lib/python3.10/site-packages/mmengine/runner/__init__.py", line 2, in <module>
    from ._flexible_runner import FlexibleRunner
  File "/home/zhanghui/anaconda3/envs/xtunernew/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 20, in <module>
    from mmengine.hooks import Hook
  File "/home/zhanghui/anaconda3/envs/xtunernew/lib/python3.10/site-packages/mmengine/hooks/__init__.py", line 9, in <module>
    from .naive_visualization_hook import NaiveVisualizationHook
  File "/home/zhanghui/anaconda3/envs/xtunernew/lib/python3.10/site-packages/mmengine/hooks/naive_visualization_hook.py", line 5, in <module>
    import cv2
  File "/home/zhanghui/anaconda3/envs/xtunernew/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/zhanghui/anaconda3/envs/xtunernew/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/zhanghui/anaconda3/envs/xtunernew/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by zhanghui-china** [comment]
<img width="710" alt="2d91a39f5fad2d9fc494d021c9593d8" src="https://github.com/InternLM/xtuner/assets/63148804/93e3ecba-9fa6-4b5e-bcea-5bdccf9f496f">

**Comment by LZHgrla** [comment]
看起来是系统环境及opencv的问题。
百度谷歌上有一些类似解决方案，可以在你的开发环境尝试一下。如果解决了，欢迎在该issue下留言以方便其他类似情况的用户解决该问题～

**Comment by zhanghui-china** [comment]
谢谢
sudo apt install libgl1-mesa-glx
安装这个时候就可以运行了。
<img width="1052" alt="2586c847bab0fd7c72a10c113d36f22" src="https://github.com/InternLM/xtuner/assets/63148804/8e3e0765-da0a-4a78-a4c3-f0b0bcb7fcac">
<img width="827" alt="2c82b98397e10e0b68baa5b1704435a" src="https://github.com/InternLM/xtuner/assets/63148804/51c93da6-b559-47a2-a5f2-7fe53d278ea0">

<img width="1088" alt="95ea90180311bbcd776872c9a0fe474" src="https://github.com/InternLM/xtuner/assets/63148804/b90d2209-3a65-40b5-ad67-1d4ed669bb0f">
<img width="1099" alt="ec404dc6b64d34b2786e09af8719733" src="https://github.com/InternLM/xtuner/assets/63148804/9add4794-5989-4c26-8b68-0c46c12b77d3">

**Comment by zhanghui-china** [comment]
<img width="962" alt="66b3b1571c95cc6747c7ba049181140" src="https://github.com/InternLM/xtuner/assets/63148804/bef70976-7b11-45c5-9ee9-55dfdecc122f">
已经可以微调了。
