### ISSUE TITLE
xtuner训练后无法使用text-generation推理

### ISSUE THREAD

**Issue by TS10armourer** [InternLM/xtuner#345]
text-generation报错如下：
```
Traceback (most recent call last):
  File "/home/tangshi/TangShi/Tools/text-generation-webui/modules/text_generation.py", line 370, in generate_reply_HF
    new_content = get_reply_from_output_ids(output, state, starting_from=starting_from)
  File "/home/tangshi/TangShi/Tools/text-generation-webui/modules/text_generation.py", line 268, in get_reply_from_output_ids
    if (hasattr(shared.tokenizer, 'convert_ids_to_tokens') and len(output_ids) > starting_from and shared.tokenizer.convert_ids_to_tokens(int(output_ids[starting_from])).startswith('▁')) and not reply.startswith(' '):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
Output generated in 2.54 seconds (0.39 tokens/s, 1 tokens, context 656, seed 149067463)
Traceback (most recent call last):
  File "/home/tangshi/TangShi/Tools/text-generation-webui/modules/text_generation.py", line 370, in generate_reply_HF
    new_content = get_reply_from_output_ids(output, state, starting_from=starting_from)
  File "/home/tangshi/TangShi/Tools/text-generation-webui/modules/text_generation.py", line 268, in get_reply_from_output_ids
    if (hasattr(shared.tokenizer, 'convert_ids_to_tokens') and len(output_ids) > starting_from and shared.tokenizer.convert_ids_to_tokens(int(output_ids[starting_from])).startswith('▁')) and not reply.startswith(' '):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by LZHgrla** [comment]
https://github.com/oobabooga/text-generation-webui/pull/5045
看起来这是 text-generation-webui 的 bug，且已被修复，请尝试安装最新的 text-generation-webui

**Comment by Egber1t** [comment]
请问这个项目的推理耗费显存大吗
