### ISSUE TITLE
训练internLM2报错

### ISSUE THREAD

**Issue by xiaohangguo** [InternLM/xtuner#347]
## pip version list
```
xtuner                        0.1.13             /public/home/lvshuhang/xtuner/xtuner_git/xtuner
torch                         2.1.0+cu118
torchaudio                    2.1.0+cu118
torchvision                   0.16.0+cu118
transformers                  4.36.2
datasets                      2.16.1
```

训练 internLM2报错
```
Traceback (most recent call last):
  File "/public/home/lvshuhang/xtuner/xtuner_git/xtuner/xtuner/tools/train.py", line 299, in <module>
    main()
  File "/public/home/lvshuhang/xtuner/xtuner_git/xtuner/xtuner/tools/train.py", line 295, in main
    runner.train()
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/runner/_flexible_runner.py", line 1200, in train
    model = self.train_loop.run()  # type: ignore
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/_strategy/deepspeed.py", line 128, in train_step
    losses = self._run_forward(data, mode='loss')
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/mmengine/_strategy/deepspeed.py", line 171, in _run_forward
    results = self.model(**data, mode=mode)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1818, in forward
    loss = self.module(*inputs, **kwargs)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'input_ids'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/public/home/lvshuhang/miniconda3/envs/xtuner/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 74, in load
    loaded_dict = pickle.load(handle)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by LZHgrla** [comment]
请贴一下所使用的训练命令

**Comment by xiaohangguo** [comment]
> @xiaohangguo 请贴一下所使用的训练命令

更新了一下，看看

**Comment by LZHgrla** [comment]
@xiaohangguo 
我这边环境无法复现，请尝试训练已有的config，验证能否复现

**Comment by xiaohangguo** [comment]
> @xiaohangguo 我这边环境无法复现，请尝试训练已有的config，验证能否复现
> 
> 例如
> 
> ```
> srun -p XXXX --job-name=xtuner --nodes=2 --gres=gpu:4 --ntasks-per-node=4 xtuner train xtuner/configs/internlm/internlm2_chat_7b/internlm2_chat_7b_qlora_oasst1_e3.py --launcher slurm --deepspeed deepspeed_zero2
> ```

@LZHgrla chatglm3 训练正常

`srun -p gpu --job-name=xtuner --nodes=2 --gres=gpu:4 --ntasks-per-node=4 --cpus-per-task=8 --mem=200G xtuner train xtuner/configs/chatglm/chatglm3_6b/chatglm3_6b_qlora_alpaca_e3.py --launcher slurm --deepspeed /public/home/lvshuhang/xtuner/xtuner/configs/deepspeed/deepspeed_zero2.json`

**Comment by xiaohangguo** [comment]
> > @xiaohangguo 我这边环境无法复现，请尝试训练已有的config，验证能否复现
> > 例如
> > ```
> > srun -p XXXX --job-name=xtuner --nodes=2 --gres=gpu:4 --ntasks-per-node=4 xtuner train xtuner/configs/internlm/internlm2_chat_7b/internlm2_chat_7b_qlora_oasst1_e3.py --launcher slurm --deepspeed deepspeed_zero2
> > ```
> 
> @LZHgrla chatglm3 训练正常
> 
> `srun -p gpu --job-name=xtuner --nodes=2 --gres=gpu:4 --ntasks-per-node=4 --cpus-per-task=8 --mem=200G xtuner train xtuner/configs/chatglm/chatglm3_6b/chatglm3_6b_qlora_alpaca_e3.py --launcher slurm --deepspeed /public/home/lvshuhang/xtuner/xtuner/configs/deepspeed/deepspeed_zero2.json`

@LZHgrla 找到bug了，加了就会爆上述bug
```
    sampler=dict(
        type=LengthGroupedSampler,
        length_property='length',
        per_device_batch_size=batch_size * accumulative_counts)
```
