### ISSUE TITLE
微调interlm20b-chat报错：UnicodeEncodeError: 'ascii' codec can't encode characters in position 28-39: ordinal not in range(128)

### ISSUE THREAD

**Issue by Egber1t** [InternLM/xtuner#418]
训练到第500个iter突然报错：Traceback (most recent call last):
  File "/root/autodl-tmp/xtuner/xtuner/tools/train.py", line 307, in <module>
    main()
  File "/root/autodl-tmp/xtuner/xtuner/tools/train.py", line 303, in main
    runner.train()
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1200, in train
    model = self.train_loop.run()  # type: ignore
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/loops.py", line 286, in run
    self.run_iter(data_batch)
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/loops.py", line 312, in run_iter
    self.runner.call_hook(
  File "/root/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1271, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "/root/autodl-tmp/xtuner/xtuner/engine/hooks/evaluate_chat_hook.py", line 240, in after_train_iter
    self._generate_samples(runner, save_eval_output=save_eval_output)
  File "/root/autodl-tmp/xtuner/xtuner/engine/hooks/evaluate_chat_hook.py", line 205, in _generate_samples
    self._eval_language(runner, model, device, max_new_tokens,
  File "/root/autodl-tmp/xtuner/xtuner/engine/hooks/evaluate_chat_hook.py", line 181, in _eval_language
    self._save_eval_output(runner, eval_outputs)
  File "/root/autodl-tmp/xtuner/xtuner/engine/hooks/evaluate_chat_hook.py", line 94, in _save_eval_output
    f.write(f'Eval output {i + 1}:\n{output}\n\n')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 28-39: ordinal not in range(128)

**Comment by Egber1t** [comment]
换成internlm2-7b-chat，在同一批数据集下，没有报错能运行成功
求解答

**Comment by LZHgrla** [comment]
问题出在保存evaluate_chat_hook的生成结果上，可以查看一下log确认一下500个iter时生成的文本是什么，进而确认一下为何会在此处出错

**Comment by LZHgrla** [comment]
感谢 @wiryls 
已在 https://github.com/InternLM/xtuner/pull/477 中修复！
