### ISSUE TITLE
deepspeed超时问题

### ISSUE THREAD

**Issue by chynphh** [InternLM/xtuner#438]
在训练llava_internlm2_chat_1_8b_clip_vit_large_p14_336的时候，加载训练数据超时，有地方修改deepspeed的默认超时时间嘛
```
[E socket.cpp:860] [c10d] The client socket has timed out after 1800s while trying to connect to (33.97.225.68, 58787).
Traceback (most recent call last):
  File "/checkpoint/binary/train_package/xtuner/xtuner/tools/train.py", line 307, in <module>
    main()
  File "/checkpoint/binary/train_package/xtuner/xtuner/tools/train.py", line 303, in main
    runner.train()
  File "/root/.local/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1182, in train
    self.strategy.prepare(
  File "/root/.local/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 386, in prepare
    self.model = self._wrap_model(model)
  File "/root/.local/lib/python3.10/site-packages/xtuner/engine/_strategy/deepspeed.py", line 19, in _wrap_model
    wrapper = super()._wrap_model(model)
  File "/root/.local/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 401, in _wrap_model
    engine, self.optim_wrapper.optimizer, *_ = deepspeed.initialize(
  File "/root/.local/lib/python3.10/site-packages/deepspeed/__init__.py", line 140, in initialize
    dist.init_distributed(dist_backend=dist_backend, dist_init_required=dist_init_required)
  File "/root/.local/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 670, in init_distributed
    cdb = TorchBackend(dist_backend, timeout, init_method, rank, world_size)
  File "/root/.local/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 121, in __init__
    self.init_process_group(backend, timeout, init_method, rank, world_size)
  File "/root/.local/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 149, in init_process_group
    torch.distributed.init_process_group(backend,
  File "/opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/opt/conda/envs/python3.10.13/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
TimeoutError: The client socket has timed out after 1800s while trying to connect to (33.97.225.68, 58787).```

**Comment by chynphh** [comment]
是多机训练

**Comment by LZHgrla** [comment]
@chynphh 
这一报错看起来是在“模型准备”阶段的通信超时，而非处理数据。

一般来说，“模型准备”阶段不应超时1800s，所以优先考虑是通信的问题。

可以贴一下起多机训练的命令，看一下是否会有问题。同时也可以检查一下多机通信是否正常。

**Comment by chynphh** [comment]
@LZHgrla 看起来像是数据处理时间不一样，有机器很快，处理完后进入模型加载阶段，但有的机器还在数据处理阶段。

**Comment by pppppM** [comment]
@chynphh 或者尝试下设置 `XTUNER_DATASET_TIMEOUT`，单位为分钟

不过像 @LZHgrla 说的一样，看 log 不像是 dataset 部分的超时

**Comment by chynphh** [comment]
@LZHgrla @pppppM 搞定了，确实是启动的问题。加了--launcher pytorch就好了。
@LZHgrla 提到只有rank0才会加载数据，通过其他机器也在加载数据反查到是多机训练的问题。然后2台机器跑起来完全是当作单机在跑..
