### ISSUE TITLE
TypeError: scaled_dot_product_attention() got an unexpected keyword argument 'training' in <xtuner.engine.hooks.evaluate_chat_hook.EvaluateChatHook object at 0x7f1ce9adfe20>

### ISSUE THREAD

**Issue by QB-Chen** [InternLM/xtuner#515]
Traceback (most recent call last):
  File "/root/xtuner/xtuner/tools/train.py", line 337, in <module>
    main()
  File "/root/xtuner/xtuner/tools/train.py", line 333, in main
    runner.train()
  File "/root/.conda/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1200, in train
    model = self.train_loop.run()  # type: ignore
  File "/root/.conda/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/loops.py", line 270, in run
    self.runner.call_hook('before_train')
  File "/root/.conda/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1273, in call_hook
    raise TypeError(f'{e} in {hook}') from e
TypeError: scaled_dot_product_attention() got an unexpected keyword argument 'training' in <xtuner.engine.hooks.evaluate_chat_hook.EvaluateChatHook object at 0x7f1ce9adfe20>

**Comment by LZHgrla** [comment]
@QB-Chen 
This error have been fixed by https://github.com/InternLM/xtuner/pull/513

Please update your xtuner library.
