### ISSUE TITLE
无法正常微调模型 缺少mpi4py

### ISSUE THREAD

**Issue by LTtt456c** [InternLM/xtuner#592]
detect MPI environment...
Traceback (most recent call last):
  File "/root/XTuner/xtuner/tools/train.py", line 342, in <module>
    main()
  File "/root/XTuner/xtuner/tools/train.py", line 338, in main
    runner.train()
  File "/root/.conda/envs/llama3/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1182, in train
    self.strategy.prepare(
  File "/root/.conda/envs/llama3/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 386, in prepare
    self.model = self._wrap_model(model)
  File "/root/XTuner/xtuner/engine/_strategy/deepspeed.py", line 25, in _wrap_model
    wrapper = super()._wrap_model(model)
  File "/root/.conda/envs/llama3/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 401, in _wrap_model
    engine, self.optim_wrapper.optimizer, *_ = deepspeed.initialize(
  File "/root/.conda/envs/llama3/lib/python3.10/site-packages/deepspeed/__init__.py", line 143, in initialize
    dist.init_distributed(dist_backend=dist_backend,
  File "/root/.conda/envs/llama3/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 658, in init_distributed
    mpi_discovery(distributed_port=distributed_port, verbose=verbose)
  File "/root/.conda/envs/llama3/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 677, in mpi_discovery
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'

**Comment by QiuZiXian** [comment]
@LTtt456c 你好，请问怎么解决

**Comment by LTtt456c** [comment]
> @LTtt456c 你好，请问怎么解决

用cuda安装依赖
