### ISSUE TITLE
xtuner TypeError: cannot pickle 'module' object

### ISSUE THREAD

**Issue by awzhgw** [InternLM/xtuner#607]
无法启动。。报错如下：

```python
[2024-04-24 06:15:17,671] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-04-24 06:15:19,718] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-04-24 06:15:19,830] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
cfg:  Config (path: /export/App/training_platform/PinoModel/xtuner/xtuner/configs/llava/llama3_8b_v1.6/pretrain/llava_llama3_8b_v1.6_pretrain.py): {'torch': torch, 'os': <module 'os' from '/usr/lib/python3.10/os.py'>, 'DefaultSampler': DefaultSampler, 'CheckpointHook': CheckpointHook, 'DistSamplerSeedHook': DistSamp
lerSeedHook, 'IterTimerHook': IterTimerHook, 'LoggerHook': LoggerHook, 'ParamSchedulerHook': ParamSchedulerHook, 'AmpOptimWrapper': AmpOptimWrapper, 'CosineAnnealingLR': CosineAnnealingLR, 'LinearLR': LinearLR, 'AdamW': AdamW, 'AutoModelForCausalLM': AutoModelForCausalLM, 'AutoTokenizer': AutoTokenizer, 'CLIPImagePr
ocessor': CLIPImageProcessor, 'CLIPVisionModel': CLIPVisionModel, 'BitsAndBytesConfig': BitsAndBytesConfig, 'AnyShapeLLaVADataset': AnyShapeLLaVADataset, 'anyshape_llava_collate_fn': anyshape_llava_collate_fn, 'llava_map_fn': llava_map_fn, 'template_map_fn_factory': template_map_fn_factory, 'DatasetInfoHook': Datase
tInfoHook, 'AnyShapeEvaluateChatHook': AnyShapeEvaluateChatHook, 'TrainLoop': TrainLoop, 'AnyShapeLLaVAModel': AnyShapeLLaVAModel, 'PROMPT_TEMPLATE': PROMPT_TEMPLATE, 'local_root': '/export/App/training_platform/PinoModel', 'llm_name_or_path': '/export/App/training_platform/PinoModel/meta-llama/Meta-Llama-3-8B-Instr
uct', 'visual_encoder_name_or_path': '/export/App/training_platform/PinoModel/openai/clip-vit-large-patch14-336', 'chubaofs_root': '/mnt/moe', 'data_root': '/mnt/moe/llama3/dataset/sharegpt4v', 'data_path': '/export/App/training_platform/PinoModel/dataset/share-captioner_coco_lcs_sam_1246k_1107.json', 'image_folder'
: '/mnt/moe/llama3/dataset/sharegpt4v/data', 'prompt_template': llama3_chat, 'max_length': 4096, 'image_grid_pinpoints': [[336, 672], [672, 336], [672, 672], [1008, 336], [336, 1008]], 'batch_size': 32, 'accumulative_counts': 2, 'dataloader_num_workers': 1, 'max_epochs': 1, 'optim_type': AdamW, 'lr': 0.001, 'betas':
 (0.9, 0.999), 'weight_decay': 0, 'max_norm': 1, 'warmup_ratio': 0.03, 'save_steps': 1000, 'save_total_limit': 2, 'evaluation_freq': 1000, 'SYSTEM': '', 'evaluation_images': '/export/App/training_platform/PinoModel/xtuner/view.jpg', 'evaluation_inputs': ['请描述一下这张照片', 'Please describe this picture'], 'tokeni
zer': {'type': from_pretrained, 'pretrained_model_name_or_path': '/export/App/training_platform/PinoModel/meta-llama/Meta-Llama-3-8B-Instruct', 'trust_remote_code': True, 'padding_side': 'right'}, 'image_processor': {'type': from_pretrained, 'pretrained_model_name_or_path': '/export/App/training_platform/PinoModel/o
penai/clip-vit-large-patch14-336', 'trust_remote_code': True}, 'model': {'type': AnyShapeLLaVAModel, 'freeze_llm': True, 'freeze_visual_encoder': True, 'image_grid_pinpoints': [[336, 672], [672, 336], [672, 672], [1008, 336], [336, 1008]], 'llm': {'type': from_pretrained, 'pretrained_model_name_or_path': '/export/Ap
p/training_platform/PinoModel/meta-llama/Meta-Llama-3-8B-Instruct', 'trust_remote_code': True, 'torch_dtype': float16, 'quantization_config': {'type': BitsAndBytesConfig, 'load_in_4bit': True, 'load_in_8bit': False, 'llm_int8_threshold': 6.0, 'llm_int8_has_fp16_weight': False, 'bnb_4bit_compute_dtype': float16, 'bnb
_4bit_use_double_quant': True, 'bnb_4bit_quant_type': 'nf4'}}, 'visual_encoder': {'type': from_pretrained, 'pretrained_model_name_or_path': '/export/App/training_platform/PinoModel/openai/clip-vit-large-patch14-336'}}, 'llava_dataset': {'type': AnyShapeLLaVADataset, 'data_path': '/export/App/training_platform/PinoMo
del/dataset/share-captioner_coco_lcs_sam_1246k_1107.json', 'image_folder': '/mnt/moe/llama3/dataset/sharegpt4v/data', 'tokenizer': {'type': from_pretrained, 'pretrained_model_name_or_path': '/export/App/training_platform/PinoModel/meta-llama/Meta-Llama-3-8B-Instruct', 'trust_remote_code': True, 'padding_side': 'righ
t'}, 'image_processor': {'type': from_pretrained, 'pretrained_model_name_or_path': '/export/App/training_platform/PinoModel/openai/clip-vit-large-patch14-336', 'trust_remote_code': True}, 'dataset_map_fn': llava_map_fn, 'template_map_fn': {'type': template_map_fn_factory, 'template': llama3_chat}, 'max_length': 4096
, 'pad_image_to_square': False, 'image_grid_pinpoints': [[336, 672], [672, 336], [672, 672], [1008, 336], [336, 1008]]}, 'train_dataloader': {'batch_size': 32, 'num_workers': 1, 'pin_memory': True, 'dataset': {'type': AnyShapeLLaVADataset, 'data_path': '/export/App/training_platform/PinoModel/dataset/share-captioner
_coco_lcs_sam_1246k_1107.json', 'image_folder': '/mnt/moe/llama3/dataset/sharegpt4v/data', 'tokenizer': {'type': from_pretrained, 'pretrained_model_name_or_path': '/export/App/training_platform/PinoModel/meta-llama/Meta-Llama-3-8B-Instruct', 'trust_remote_code': True, 'padding_side': 'right'}, 'image_processor': {'t
ype': from_pretrained, 'pretrained_model_name_or_path': '/export/App/training_platform/PinoModel/openai/clip-vit-large-patch14-336', 'trust_remote_code': True}, 'dataset_map_fn': llava_map_fn, 'template_map_fn': {'type': template_map_fn_factory, 'template': llama3_chat}, 'max_length': 4096, 'pad_image_to_square': Fa
lse, 'image_grid_pinpoints': [[336, 672], [672, 336], [672, 672], [1008, 336], [336, 1008]]}, 'sampler': {'type': DefaultSampler, 'shuffle': True}, 'collate_fn': {'type': anyshape_llava_collate_fn}}, 'optim_wrapper': {'type': AmpOptimWrapper, 'optimizer': {'type': AdamW, 'lr': 0.001, 'betas': (0.9, 0.999), 'weight_d
ecay': 0}, 'clip_grad': {'max_norm': 1, 'error_if_nonfinite': False}, 'accumulative_counts': 2, 'loss_scale': 'dynamic', 'dtype': 'float16'}, 'param_scheduler': [{'type': LinearLR, 'start_factor': 1e-05, 'by_epoch': True, 'begin': 0, 'end': 0.03, 'convert_to_iter_based': True}, {'type': CosineAnnealingLR, 'eta_min':
 0.0, 'by_epoch': True, 'begin': 0.03, 'end': 1, 'convert_to_iter_based': True}], 'train_cfg': {'type': TrainLoop, 'max_epochs': 1}, 'custom_hooks': [{'type': DatasetInfoHook, 'tokenizer': {'type': from_pretrained, 'pretrained_model_name_or_path': '/export/App/training_platform/PinoModel/meta-llama/Meta-Llama-3-8B-I
nstruct', 'trust_remote_code': True, 'padding_side': 'right'}}, {'type': AnyShapeEvaluateChatHook, 'image_grid_pinpoints': [[336, 672], [672, 336], [672, 672], [1008, 336], [336, 1008]], 'tokenizer': {'type': from_pretrained, 'pretrained_model_name_or_path': '/export/App/training_platform/PinoModel/meta-llama/Meta-L
lama-3-8B-Instruct', 'trust_remote_code': True, 'padding_side': 'right'}, 'image_processor': {'type': from_pretrained, 'pretrained_model_name_or_path': '/export/App/training_platform/PinoModel/openai/clip-vit-large-patch14-336', 'trust_remote_code': True}, 'every_n_iters': 1000, 'evaluation_inputs': ['请描述一下这张
照片', 'Please describe this picture'], 'evaluation_images': '/export/App/training_platform/PinoModel/xtuner/view.jpg', 'system': '', 'prompt_template': llama3_chat}], 'default_hooks': {'timer': {'type': IterTimerHook}, 'logger': {'type': LoggerHook, 'log_metric_by_epoch': False, 'interval': 10}, 'param_scheduler':
{'type': ParamSchedulerHook}, 'checkpoint': {'type': CheckpointHook, 'by_epoch': False, 'interval': 1000, 'max_keep_ckpts': 2}, 'sampler_seed': {'type': DistSamplerSeedHook}}, 'env_cfg': {'cudnn_benchmark': False, 'mp_cfg': {'mp_start_method': 'fork', 'opencv_num_threads': 0}, 'dist_cfg': {'backend': 'nccl'}}, 'visu
alizer': None, 'log_level': 'INFO', 'load_from': None, 'resume': False, 'randomness': {'seed': None, 'deterministic': False}, 'log_processor': {'by_epoch': False}}
04/24 06:15:20 - mmengine - INFO - Set the random seed to 1024.
Traceback (most recent call last):
  File "/export/App/training_platform/PinoModel/xtuner/xtuner/tools/train.py", line 342, in <module>
    main()
  File "/export/App/training_platform/PinoModel/xtuner/xtuner/tools/train.py", line 335, in main
    runner = RUNNERS.build(cfg)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 196, in build_runner_from_cfg
    runner = runner_cls.from_cfg(args)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/_flexible_runner.py", line 422, in from_cfg
    cfg = copy.deepcopy(cfg)
  File "/usr/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 1527, in __deepcopy__
    super(Config, other).__setattr__(key, copy.deepcopy(value, memo))
  File "/usr/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 144, in __deepcopy__
    other[copy.deepcopy(key, memo)] = copy.deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'module' object
```

**Comment by SihengLi99** [comment]
请问怎么解决的？

**Comment by labor784** [comment]
请问解决了吗？

**Comment by Chrono-Chasm** [comment]
答案是在配置文件末尾del os
