### ISSUE TITLE
用xtuner在V100上训练internlm-7b模型出现OOM错误

### ISSUE THREAD

**Issue by haoxufd** [InternLM/xtuner#616]
环境：v100，torch2.1.0+cu118，xtuner0.1.18
在v100上跑 [Ready-to-use models and datasets from XTuner API](https://colab.research.google.com/drive/17CSO7T8q6KePuvu684IiHl6_id-CjPjh?usp=sharing) 所示的demo(用xtuner训练internlm-7b)，出现OOM错误，完整的log如下：
<details><summary>Details</summary>
<p>

[2024-04-25 15:58:28,178] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  NVIDIA Inference is only supported on Ampere and newer architectures
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
`low_cpu_mem_usage` was None, now set to True since model is quantized.
Loading checkpoint shards:   0%|                                                                                      | 0/8 [00:00<?, ?it/s]/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████| 8/8 [00:11<00:00,  1.49s/it]
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
04/25 15:58:45 - mmengine - INFO - replace internlm rope
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
Flattening the indices (num_proc=32): 100%|██████████████████████████████████████████████████| 51979/51979 [00:21<00:00, 2455.34 examples/s]
Map (num_proc=32): 100%|█████████████████████████████████████████████████████████████████████| 51979/51979 [00:18<00:00, 2764.48 examples/s]
Map (num_proc=32): 100%|████████████████████████████████████████████████████████████████████████| 2262/2262 [00:19<00:00, 118.87 examples/s]
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
max_steps is given, it will override any value given in num_train_epochs
  0%|                                                                                                                 | 0/5 [00:00<?, ?it/s]/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
 20%|█████████████████████                                                                                    | 1/5 [01:35<06:23, 95.89s/it]Traceback (most recent call last):
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xuhao/.vscode-server/extensions/ms-python.debugpy-2024.4.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/xuhao/.vscode-server/extensions/ms-python.debugpy-2024.4.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/xuhao/.vscode-server/extensions/ms-python.debugpy-2024.4.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/xuhao/.vscode-server/extensions/ms-python.debugpy-2024.4.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/xuhao/.vscode-server/extensions/ms-python.debugpy-2024.4.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/xuhao/.vscode-server/extensions/ms-python.debugpy-2024.4.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/xuhao/test_xtuner/xtuner_for_hf_example.py", line 74, in <module>
    trainer.train()
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/transformers/trainer.py", line 3138, in training_step
    loss = self.compute_loss(model, inputs)
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/transformers/trainer.py", line 3161, in compute_loss
    outputs = model(**inputs)
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 186, in forward
    return self.gather(outputs, self.output_device)
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 203, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/nn/parallel/scatter_gather.py", line 105, in gather
    res = gather_map(outputs)
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/nn/parallel/scatter_gather.py", line 96, in gather_map
    return type(out)((k, gather_map([d[k] for d in outputs]))
  File "<string>", line 8, in __init__
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/transformers/utils/generic.py", line 393, in __post_init__
    for idx, element in enumerate(iterator):
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/nn/parallel/scatter_gather.py", line 96, in <genexpr>
    return type(out)((k, gather_map([d[k] for d in outputs]))
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/nn/parallel/scatter_gather.py", line 90, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/nn/parallel/_functions.py", line 75, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/nvme/llm_env/miniconda3-py310_4/envs/xtuner-env/lib/python3.10/site-packages/torch/nn/parallel/comm.py", line 231, in gather
    return torch._C._gather(tensors, dim, destination)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.30 GiB. GPU 0 has a total capacty of 31.75 GiB of which 4.08 GiB is free. Including non-PyTorch memory, this process has 27.66 GiB memory in use. Of the allocated memory 23.14 GiB is allocated by PyTorch, and 2.99 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 20%|██        | 1/5 [02:33<10:14, 153.52s/it]

</p>
</details>

**Comment by LZHgrla** [comment]
@haoxufd 
我刚刚尝试了一下该demo在colab上是能跑通的。所以推测是环境安装的问题。

同时，该demo所对应的apis用法已经处于半弃用状态，建议参照readme https://github.com/InternLM/xtuner?tab=readme-ov-file#fine-tune- 来进行训练、微调。
