### ISSUE TITLE
pth_to_hf error: Phi3ForCausalLM does not support an attention implementation through torch.nn.functional.scaled_dot_product_attention

### ISSUE THREAD

**Issue by rezacopol** [InternLM/xtuner#633]
Trying to follow the instruction [here](https://github.com/InternLM/xtuner/tree/main/xtuner/configs/llava/phi3_mini_4k_instruct_clip_vit_large_p14_336)

stuck at first step:
xtuner convert pth_to_hf llava_phi3_mini_4k_instruct_clip_vit_large_p14_336_e1_gpu8_sharegpt4v_pretrain  ./iter_9742.pth ./iter_9742_xtuner

Here is the error:
`[2024-04-30 17:35:58,185] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.0), only 1.0.0 is known to be compatible
[2024-04-30 17:36:02,546] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.0), only 1.0.0 is known to be compatible
`flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
Current `flash-attenton` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.
Traceback (most recent call last):
  File "/mnt/task_runtime/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 143, in <module>
    main()
  File "/mnt/task_runtime/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 65, in main
    model = BUILDER.build(cfg.model)
  File "/miniconda/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/miniconda/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/task_runtime/xtuner/xtuner/model/llava.py", line 42, in __init__
    self.llm = self._build_from_cfg_or_module(llm)
  File "/mnt/task_runtime/xtuner/xtuner/model/llava.py", line 239, in _build_from_cfg_or_module
    return BUILDER.build(cfg_or_mod)
  File "/miniconda/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/miniconda/envs/xtuner-env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/miniconda/envs/xtuner-env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/miniconda/envs/xtuner-env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3544, in from_pretrained
    config = cls._autoset_attn_implementation(
  File "/miniconda/envs/xtuner-env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1463, in _autoset_attn_implementation
    config = cls._check_and_enable_sdpa(
  File "/miniconda/envs/xtuner-env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1619, in _check_and_enable_sdpa
    raise ValueError(
ValueError: Phi3ForCausalLM does not support an attention implementation through torch.nn.functional.scaled_dot_product_attention yet. Please request the support for this architecture: https://github.com/huggingface/transformers/issues/28005. If you believe this error is a bug, please open an issue in Transformers GitHub repository and load your model with the argument `attn_implementation="eager"` meanwhile. Example: `model = AutoModel.from_pretrained("openai/whisper-tiny", attn_implementation="eager")`
`

where I got the pth file from here: 
https://huggingface.co/xtuner/llava-phi-3-mini-pretrain

Cuda version: 12.2
torch version: 2.3.0+cu121
transformers: 4.40.1

**Comment by rezacopol** [comment]
issue was with flash attention

**Comment by shockjiang** [comment]
@rezacopol 
even the issue was with flash attention, I wonder how to avoid it in xtuner. 

for now I set attn_implementation="eager", does this produce expect to be the same accuray after training?

thx.

**Comment by Mikael17125** [comment]
> @rezacopol even the issue was with flash attention, I wonder how to avoid it in xtuner.
> 
> for now I set attn_implementation="eager", does this produce expect to be the same accuray after training?
> 
> thx.

Which part should I change?

**Comment by bjzhb666** [comment]
How to solve this? Thanks
