### ISSUE TITLE
怎么从上一个checkpoint中继续训练呢？

### ISSUE THREAD

**Issue by awzhgw** [InternLM/xtuner#635]
当我尝试使用llava_phi3的模型在finetune阶段。在训练的过程中，不小心杀了进程。。

# load from which checkpoint
load_from = '{}/work_dir/iter_7500.pth'.format(local_root)

其中iter_7500.pth 是一个文件。。而不是目录。。

当我reload的时候，报错了：

```shell
05/01 07:36:57 - mmengine - INFO - Load checkpoint from /export/App/training_platform/PinoModel/work_dir/iter_7500.pth
Traceback (most recent call last):
  File "/export/App/training_platform/PinoModel/xtuner/xtuner/tools/train.py", line 344, in <module>
    main()
  File "/export/App/training_platform/PinoModel/xtuner/xtuner/tools/train.py", line 340, in main
    runner.train()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/_flexible_runner.py", line 1195, in train
    self.load_or_resume()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/_flexible_runner.py", line 1144, in load_or_resume
    self.load_checkpoint(self._load_from)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/_flexible_runner.py", line 1528, in load_checkpoint
    self.strategy.load_checkpoint(
  File "/export/App/training_platform/PinoModel/xtuner/xtuner/engine/_strategy/deepspeed.py", line 51, in load_checkpoint
    checkpoint = super().load_checkpoint(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/_strategy/deepspeed.py", line 434, in load_checkpoint
    _, extra_ckpt = self.model.load_checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 2764, in load_checkpoint
    load_path, client_states = self._load_checkpoint(load_dir,
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 2814, in _load_checkpoint
    sd_loader = SDLoaderFactory.get_sd_loader(ckpt_list, checkpoint_engine=self.checkpoint_engine)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/state_dict_factory.py", line 43, in get_sd_loader
    return MegatronSDLoader(ckpt_list, version, checkpoint_engine)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/state_dict_factory.py", line 193, in __init__
    super().__init__(ckpt_list, version, checkpoint_engine)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/state_dict_factory.py", line 55, in __init__
    self.check_ckpt_list()
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/state_dict_factory.py", line 168, in check_ckpt_list
    assert len(self.ckpt_list) > 0
AssertionError
[2024-05-01 07:37:00,705] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 99837) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
```

**Comment by sunye23** [comment]
> 当我尝试使用llava_phi3的模型在finetune阶段。在训练的过程中，不小心杀了进程。。
> 
> # load from which checkpoint
> load_from = '{}/work_dir/iter_7500.pth'.format(local_root)
> 
> 其中iter_7500.pth 是一个文件。。而不是目录。。
> 
> 当我reload的时候，报错了：
> 
> 05/01 07:36:57 - mmengine - INFO - Load checkpoint from /export/App/training_platform/PinoModel/work_dir/iter_7500.pth
> Traceback (most recent call last):
>   File "/export/App/training_platform/PinoModel/xtuner/xtuner/tools/train.py", line 344, in <module>
>     main()
>   File "/export/App/training_platform/PinoModel/xtuner/xtuner/tools/train.py", line 340, in main
>     runner.train()
>   File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/_flexible_runner.py", line 1195, in train
>     self.load_or_resume()
>   File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/_flexible_runner.py", line 1144, in load_or_resume
>     self.load_checkpoint(self._load_from)
>   File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/_flexible_runner.py", line 1528, in load_checkpoint
>     self.strategy.load_checkpoint(
>   File "/export/App/training_platform/PinoModel/xtuner/xtuner/engine/_strategy/deepspeed.py", line 51, in load_checkpoint
>     checkpoint = super().load_checkpoint(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/mmengine/_strategy/deepspeed.py", line 434, in load_checkpoint
>     _, extra_ckpt = self.model.load_checkpoint(
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 2764, in load_checkpoint
>     load_path, client_states = self._load_checkpoint(load_dir,
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 2814, in _load_checkpoint
>     sd_loader = SDLoaderFactory.get_sd_loader(ckpt_list, checkpoint_engine=self.checkpoint_engine)
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/state_dict_factory.py", line 43, in get_sd_loader
>     return MegatronSDLoader(ckpt_list, version, checkpoint_engine)
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/state_dict_factory.py", line 193, in __init__
>     super().__init__(ckpt_list, version, checkpoint_engine)
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/state_dict_factory.py", line 55, in __init__
>     self.check_ckpt_list()
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/state_dict_factory.py", line 168, in check_ckpt_list
>     assert len(self.ckpt_list) > 0
> AssertionError
> [2024-05-01 07:37:00,705] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 99837) of binary: /usr/bin/python
> Traceback (most recent call last):
>   File "/usr/local/bin/torchrun", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 806, in main
>     run(args)
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
>     elastic_launch(
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> ============================================================

兄弟你还记得这个问题怎么解决的吗。。
