### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by laozhai507** [InternLM/xtuner#762]
Last month, I can ran this set of script without problems, but now I have the following error:
- Script: `xtuner train xtuner/xtuner/configs/llava/llama3_8b_instruct_clip_vit_large_p14_336/finetune/llava_llama3_8b_instruct_qlora_clip_vit_large_p14_336_e1_gpu1_finetune.py`
- Model: 
    - LLM: `meta-llama/Meta-Llama-3-8B-Instruct`
    - VLLM: `openai/clip-vit-large-patch14-336`
    - projector: `xtuner/llava-llama-3-8b-v1_1-pretrain`
 - config:
```# Model
llm_name_or_path = '/hy-tmp/Meta-Llama-3-8B-Instruct'
visual_encoder_name_or_path = '/hy-tmp/clip-vit-large-patch14-336'
# Specify the pretrained pth
pretrained_pth = '/hy-tmp/llava-llama-3-8b-v1_1-pretrain/iter_9742.pth'  # noqa: E501

# Data
data_root = '/hy-tmp/mmRAG/data/'
data_path = '/hy-tmp/mmRAG/data/model_finetuning/llava_xtuner_ft_data.json'
image_folder = '/hy-tmp/mmRAG/data/MultiModalQA/final_dataset_images'
```
- data snippet:
```
[
    {
        "id": "47107895b88600baf5adee03b12fc53b",
        "image": "47107895b88600baf5adee03b12fc53b.png",
        "conversations": [
            {
                "from": "human",
                "value": "<image>\nAs a senior editor, you are asked to write a concise and comprehensive summary of the provided image, while adhering to these guidelines:\n                        - Craft an summary that is detailed, thorough, in-depth, and complex, while maintaining clarity and conciseness and as precise as possible.\n                        - Incorporate main and essential information, eliminating extraneous language and focusing on critical aspects.\n                        - Rely strictly on the provided image without external information.\n                        - Format the summary in paragraph form for easy understanding.\n"
            },
            {
                "from": "gpt",
                "value": "The provided image is a collage showcasing various landmarks and scenic views of a city nestled in a valley surrounded by mountains. The top section features a panoramic view of the city with a river winding through it, highlighting the urban landscape against a backdrop of lush hills. The middle section includes images of modern and historical architecture: a strikingly contemporary building with metallic, curvilinear forms, a narrow street with a glass ceiling, a classical building with ornate details, and a riverside structure with a prominent tower. Additionally, there is a large, colorful sculpture of a dog covered in flowers, a grand theater, and an interior view of a modern, geometric space. The bottom section displays vibrant urban scenes, including a bustling plaza, a red suspension bridge, and a detailed, ornate interior of a building. The collage collectively captures the architectural diversity, cultural richness, and scenic beauty of the city."
            }
        ]
    },...
```
- error message:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/_flexible_runner.py", line 1271, in call_hook
[rank0]:     getattr(hook, fn_name)(self, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/xtuner/engine/hooks/evaluate_chat_hook.py", line 230, in before_train
[rank0]:     self._generate_samples(runner, max_new_tokens=50)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/xtuner/engine/hooks/evaluate_chat_hook.py", line 216, in _generate_samples
[rank0]:     self._eval_images(runner, model, device, max_new_tokens,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/xtuner/engine/hooks/evaluate_chat_hook.py", line 148, in _eval_images
[rank0]:     generation_output = model.generate(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 1491, in generate
[rank0]:     outputs = self.base_model.generate(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1758, in generate
[rank0]:     result = self._sample(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2390, in _sample
[rank0]:     model_kwargs = self._get_initial_cache_position(input_ids, model_kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1321, in _get_initial_cache_position
[rank0]:     past_length = model_kwargs["past_key_values"][0][0].shape[2]
[rank0]: TypeError: 'NoneType' object is not subscriptable
```

**Comment by hhaAndroid** [comment]
@laozhai507 It could be an issue with the transforms version. Can you try using a different version?

**Comment by dacian7** [comment]
> > @laozhai507 It could be an issue with the transforms version. Can you try using a different version?
> 
> @hhaAndroid Thank you for your advise. I used another framework to achieve my goal.

@laozhai507 May I ask which one did you use? Thanks!
