### ISSUE TITLE
关于Qwen1.5 32B-Chat 训练的问题

### ISSUE THREAD

**Issue by wgs97** [InternLM/xtuner#793]
很奇怪的问题是，在8*A100（80G）上无论我如何设置max-seq，从16000降到200，始终都会OOM。
如下是我的命令和配置：

NPROC_PER_NODE=8 nohup xtuner train qwen1_5_32b_chat --deepspeed deepspeed_zero3 > instruct.out 2>&1 &

#######################################################################
#                          PART 1  Settings                           #
#######################################################################
# Model
pretrained_model_name_or_path = '/home/fenbi/ai-teacher/model/Qwen1.5-32B-Chat'
use_varlen_attn = False

# Data
data_files = ['test.json']
prompt_template = PROMPT_TEMPLATE.qwen_chat
max_length = 200 
pack_to_max_length = False 

# parallel
sequence_parallel_size = 1 

# Scheduler & Optimizer
batch_size = 1  # per_device
# total batch = 32gpus * batch_size_per_device 1 * acc 1 = 32
accumulative_counts = 1
accumulative_counts *= sequence_parallel_size
dataloader_num_workers = 0 
max_epochs = 3
optim_type = AdamW
lr = 1e-5
betas = (0.9, 0.999)
weight_decay = 0
max_norm = 1  # grad clip
warmup_ratio = 0.03

# Save
save_steps = 500
save_total_limit = 1  # Maximum checkpoints to keep (-1 means unlimited)

#######################################################################
#                      PART 2  Model & Tokenizer                      #
#######################################################################
tokenizer = dict(
    type=AutoTokenizer.from_pretrained,
    pretrained_model_name_or_path=pretrained_model_name_or_path,
    trust_remote_code=True,
    padding_side='right')

model = dict(
    type=SupervisedFinetune,
    use_varlen_attn=use_varlen_attn,
    llm=dict(
        type=AutoModelForCausalLM.from_pretrained,
        pretrained_model_name_or_path=pretrained_model_name_or_path,
        trust_remote_code=True,
        torch_dtype=torch.float16))

#######################################################################
#                      PART 3  Dataset & Dataloader                   #
#######################################################################
sampler = SequenceParallelSampler \
    if sequence_parallel_size > 1 else DefaultSampler

train_dataset = dict(
    type=process_hf_dataset,
    use_varlen_attn=use_varlen_attn,
    dataset=dict(type=load_dataset, path='json', data_files=data_files),
    tokenizer=tokenizer,
    max_length=max_length,
    dataset_map_fn=None,
    template_map_fn=dict(
        type=template_map_fn_factory, template=prompt_template),
    remove_unused_columns=True,
    shuffle_before_pack=True,
    pack_to_max_length=pack_to_max_length)

train_dataloader = dict(
    batch_size=batch_size,
    num_workers=dataloader_num_workers,
    dataset=train_dataset,
    sampler=dict(type=sampler, shuffle=True),
    collate_fn=dict(type=default_collate_fn, use_varlen_attn=use_varlen_attn))

#######################################################################
#                    PART 4  Scheduler & Optimizer                    #
#######################################################################
# optimizer
optim_wrapper = dict(
    type=AmpOptimWrapper,
    optimizer=dict(
        type=optim_type, lr=lr, betas=betas, weight_decay=weight_decay),
    clip_grad=dict(max_norm=max_norm, error_if_nonfinite=False),
    accumulative_counts=accumulative_counts,
    loss_scale='dynamic',
    dtype='float16')

# learning policy
# More information: https://github.com/open-mmlab/mmengine/blob/main/docs/en/tutorials/param_scheduler.md  # noqa: E501
param_scheduler = [
    dict(
        type=LinearLR,
        start_factor=1e-5,
        by_epoch=True,
        begin=0,
        end=warmup_ratio * max_epochs,
        convert_to_iter_based=True),
    dict(
        type=CosineAnnealingLR,
        eta_min=0.0,
        by_epoch=True,
        begin=warmup_ratio * max_epochs,
        end=max_epochs,
        convert_to_iter_based=True)
]

# train, val, test setting
train_cfg = dict(type=TrainLoop, max_epochs=max_epochs)

#######################################################################
#                           PART 5  Runtime                           #
#######################################################################
# Log the dialogue periodically during the training process, optional
custom_hooks = [
    dict(type=DatasetInfoHook, tokenizer=tokenizer),
    dict(type=ThroughputHook)
]

if use_varlen_attn:
    custom_hooks += [dict(type=VarlenAttnArgsToMessageHubHook)]

# configure default hooks
default_hooks = dict(
    # record the time of every iteration.
    timer=dict(type=IterTimerHook),
    # print log every 10 iterations.
    logger=dict(type=LoggerHook, log_metric_by_epoch=False, interval=10),
    # enable the parameter scheduler.
    param_scheduler=dict(type=ParamSchedulerHook),
    # save checkpoint per `save_steps`.
    checkpoint=dict(
        type=CheckpointHook,
        by_epoch=False,
        interval=save_steps,
        max_keep_ckpts=save_total_limit),
    # set sampler seed in distributed evrionment.
    sampler_seed=dict(type=DistSamplerSeedHook),
)

# configure environment
env_cfg = dict(
    # whether to enable cudnn benchmark
    cudnn_benchmark=False,
    # set multi process parameters
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    # set distributed parameters
    dist_cfg=dict(backend='nccl'),
)

# set visualizer
visualizer = None

# set log level
log_level = 'INFO'

# load from which checkpoint
load_from = None

# whether to resume training from the loaded checkpoint
resume = True 

# Defaults to use random seed and disable `deterministic`
randomness = dict(seed=None, deterministic=False)

# set log processor
log_processor = dict(by_epoch=False)

**Comment by wgs97** [comment]
另外，在8*A100（80G）的条件下，能否支持32B-Chat + 20K 长度的训练？，

**Comment by HIT-cwh** [comment]
你好！
全量微调 32B 模型，每张卡上模型状态部分就占据了 32 * 16 / 8 = 64G 的显存，这部分显存占用不会随着序列长度的降低而减少。（计算方法参考 [如何选择 ZeRO 策略文档](https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/acceleration/deepspeed.rst#%E5%A6%82%E4%BD%95%E9%80%89%E6%8B%A9-zero-%E7%AD%96%E7%95%A5) ）

再加上激活值等其他Tensor很容易导致 OOM 。

如果想使用 8*A100（80G）训练 32B 模型，建议尝试 Lora 或 QLora 算法。如果想训练 20k 上下文，还可以尝试使用 XTuner 的序列并行策略，[参考文档](https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/acceleration/train_extreme_long_sequence.rst)

**Comment by wgs97** [comment]
> 你好！ 全量微调 32B 模型，每张卡上模型状态部分就占据了 32 * 16 / 8 = 64G 的显存，这部分显存占用不会随着序列长度的降低而减少。（计算方法参考 [如何选择 ZeRO 策略文档](https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/acceleration/deepspeed.rst#%E5%A6%82%E4%BD%95%E9%80%89%E6%8B%A9-zero-%E7%AD%96%E7%95%A5) ）
> 
> 再加上激活值等其他Tensor很容易导致 OOM 。
> 
> 如果想使用 8*A100（80G）训练 32B 模型，建议尝试 Lora 或 QLora 算法。如果想训练 20k 上下文，还可以尝试使用 XTuner 的序列并行策略，[参考文档](https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/acceleration/train_extreme_long_sequence.rst)

你好，谢谢回复，之前试过32B在LLAMA-FACTORY在ZERO3是可以训练的（不过长度较短），现在希望在长度增大时使用序列并行。不确定Xtuner和LLAMA-FACTORY两个框架，在QWEN训练上除了序列并行之外有什么不同..

**Comment by HIT-cwh** [comment]
能不能提供一份详细的报错信息呢？方便我们定位OOM发生在forward还是backward的时候。

另外，也许可以尝试下ZeRO3-Offload，但可能一定程度上拖慢训练速度。

**Comment by wgs97** [comment]
> 能不能提供一份详细的报错信息呢？方便我们定位OOM发生在forward还是backward的时候。
> 
> 另外，也许可以尝试下ZeRO3-Offload (--deepspeed deepspeed_zero3_offload)，但可能一定程度上拖慢训练速度。

你好，大致如下：

Traceback (most recent call last):
  File "/home/fenbi/wanggs/xtuner/xtuner/tools/train.py", line 360, in <module>
    main()
  File "/home/fenbi/wanggs/xtuner/xtuner/tools/train.py", line 356, in main
    runner.train()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1200, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/loops.py", line 286, in run
    self.run_iter(data_batch)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/loops.py", line 309, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 135, in train_step
    optim_wrapper.update_params(parsed_loss)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 83, in update_params
    self.step()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/optim/scheduler/param_scheduler.py", line 115, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 95, in step
    self.model.step()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2169, in step
    self._take_model_step(lr_kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2075, in _take_model_step
    self.optimizer.step()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2050, in step
    self._optimizer_step(sub_group_id)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 947, in _optimizer_step
    self.optimizer.step()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/optimizer.py", line 385, in wrapper
    out = func(*args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/adamw.py", line 187, in step
    adamw(
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/adamw.py", line 339, in adamw
    func(
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/adamw.py", line 608, in _multi_tensor_adamw
    exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.87 GiB. GPU 2 has a total capacity of 79.15 GiB of which 1.57 GiB is free. Including non-PyTorch memory, this process has 77.58 GiB memory in use. Of the allocated memory 66.38 GiB is allocated by PyTorch, and 8.56 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/fenbi/wanggs/xtuner/xtuner/tools/train.py", line 360, in <module>
    main()
  File "/home/fenbi/wanggs/xtuner/xtuner/tools/train.py", line 356, in main
    runner.train()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1200, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/loops.py", line 286, in run
    self.run_iter(data_batch)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/loops.py", line 309, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 135, in train_step
    optim_wrapper.update_params(parsed_loss)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 83, in update_params
    self.step()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/optim/scheduler/param_scheduler.py", line 115, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 95, in step
    self.model.step()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2169, in step
    self._take_model_step(lr_kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2075, in _take_model_step
Traceback (most recent call last):
  File "/home/fenbi/wanggs/xtuner/xtuner/tools/train.py", line 360, in <module>
    self.optimizer.step()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    main()
  File "/home/fenbi/wanggs/xtuner/xtuner/tools/train.py", line 356, in main
    ret_val = func(*args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2050, in step
    runner.train()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1200, in train
    self._optimizer_step(sub_group_id)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 947, in _optimizer_step
    model = self.train_loop.run()  # type: ignore
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/loops.py", line 286, in run
    self.run_iter(data_batch)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/loops.py", line 309, in run_iter
    self.optimizer.step()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/optimizer.py", line 385, in wrapper
    outputs = self.runner.model.train_step(
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 135, in train_step
    out = func(*args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    optim_wrapper.update_params(parsed_loss)
      File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 83, in update_params
ret = func(self, *args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/adamw.py", line 187, in step
    self.step()
      File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/optim/scheduler/param_scheduler.py", line 115, in wrapper
adamw(
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/adamw.py", line 339, in adamw
    return wrapped(*args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 95, in step
    func(
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/adamw.py", line 608, in _multi_tensor_adamw
    self.model.step()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2169, in step
    exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.87 GiB. GPU 6 has a total capacity of 79.15 GiB of which 1.57 GiB is free. Including non-PyTorch memory, this process has 77.58 GiB memory in use. Of the allocated memory 66.38 GiB is allocated by PyTorch, and 8.56 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
    self._take_model_step(lr_kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2075, in _take_model_step
    self.optimizer.step()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2050, in step
    self._optimizer_step(sub_group_id)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 947, in _optimizer_step
    self.optimizer.step()
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/optimizer.py", line 385, in wrapper
    out = func(*args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/adamw.py", line 187, in step
    adamw(
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/adamw.py", line 339, in adamw
    func(
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/optim/adamw.py", line 608, in _multi_tensor_adamw
    exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.87 GiB. GPU 7 has a total capacity of 79.15 GiB of which 1.85 GiB is free. Including non-PyTorch memory, this process has 77.30 GiB memory in use. Of the allocated memory 66.38 GiB is allocated by PyTorch, and 8.56 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2024-06-27 14:48:15,405] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 101275 closing signal SIGTERM
[2024-06-27 14:48:15,720] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 101270) of binary: /home/fenbi/miniconda3/envs/xtuner/bin/python
Traceback (most recent call last):
  File "/home/fenbi/miniconda3/envs/xtuner/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/fenbi/miniconda3/envs/xtuner/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by wgs97** [comment]
也许我需要试试Megatron..
