### ISSUE TITLE
使用 deepspeed_zero2 训练启动失败

### ISSUE THREAD

**Issue by online2311** [InternLM/xtuner#80]
显卡配置
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P100-PCIE-16GB           On  | 00000000:04:00.0 Off |                    0 |
| N/A   59C    P0             1W / 250W |  0MiB / 16384MiB |    0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE-16GB           On  | 00000000:42:00.0 Off |                    0 |
| N/A   59C    P0             1W / 250W |  0MiB / 16384MiB |    0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```
启动命令 

```
NPROC_PER_NODE=2 xtuner train /app/train/internlm_7b_qlora_alpaca_zh_e3/internlm_7b_qlora_alpaca_zh_e3.py --deepspeed deepspeed_zero2
```
internlm_7b_qlora_alpaca_zh_e3.py 内配置
```
# Copyright (c) OpenMMLab. All rights reserved.
import torch
from bitsandbytes.optim import PagedAdamW32bit
from datasets import load_dataset
from mmengine.dataset import DefaultSampler
from mmengine.hooks import (CheckpointHook, DistSamplerSeedHook, IterTimerHook,
                            LoggerHook, ParamSchedulerHook)
from mmengine.optim import AmpOptimWrapper, CosineAnnealingLR
from peft import LoraConfig
from transformers import (AutoModelForCausalLM, AutoTokenizer,
                          BitsAndBytesConfig)

from xtuner.dataset import process_hf_dataset
from xtuner.dataset.collate_fns import default_collate_fn
from xtuner.dataset.map_fns import alpaca_zh_map_fn, template_map_fn_factory
from xtuner.engine import DatasetInfoHook, EvaluateChatHook
from xtuner.model import SupervisedFinetune
from xtuner.utils import PROMPT_TEMPLATE

#######################################################################
#                          PART 1  Settings                           #
#######################################################################
# Model
pretrained_model_name_or_path = '/app/models/internlm_internlm-7b'

# Data
alpaca_zh_path = 'silk-road/alpaca-data-gpt4-chinese'
prompt_template = PROMPT_TEMPLATE.alpaca
max_length = 2048
pack_to_max_length = True

# Scheduler & Optimizer
batch_size = 1  # per_device
accumulative_counts = 16
dataloader_num_workers = 0
max_epochs = 3
optim_type = PagedAdamW32bit
lr = 2e-4
betas = (0.9, 0.999)
weight_decay = 0
max_norm = 1  # grad clip

# Evaluate the generation performance during the training
evaluation_freq = 500
evaluation_inputs = [
    '请给我介绍五个上海的景点', 'Please tell me five scenic spots in Shanghai'
]

#######################################################################
#                      PART 2  Model & Tokenizer                      #
#######################################################################
tokenizer = dict(
    type=AutoTokenizer.from_pretrained,
    pretrained_model_name_or_path=pretrained_model_name_or_path,
    trust_remote_code=True,
    padding_side='right')

model = dict(
    type=SupervisedFinetune,
    llm=dict(
        type=AutoModelForCausalLM.from_pretrained,
        pretrained_model_name_or_path=pretrained_model_name_or_path,
        trust_remote_code=True,
        torch_dtype=torch.float16,
        quantization_config=dict(
            type=BitsAndBytesConfig,
            load_in_4bit=True,
            load_in_8bit=False,
            llm_int8_threshold=6.0,
            llm_int8_has_fp16_weight=False,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type='nf4')),
    lora=dict(
        type=LoraConfig,
        r=64,
        lora_alpha=16,
        lora_dropout=0.1,
        bias='none',
        task_type='CAUSAL_LM'))

#######################################################################
#                      PART 3  Dataset & Dataloader                   #
#######################################################################
alpaca_zh = dict(
    type=process_hf_dataset,
    dataset=dict(type=load_dataset, path=alpaca_zh_path),
    tokenizer=tokenizer,
    max_length=max_length,
    dataset_map_fn=alpaca_zh_map_fn,
    template_map_fn=dict(
        type=template_map_fn_factory, template=prompt_template),
    remove_unused_columns=True,
    shuffle_before_pack=True,
    pack_to_max_length=pack_to_max_length)

train_dataloader = dict(
    batch_size=batch_size,
    num_workers=dataloader_num_workers,
    dataset=alpaca_zh,
    sampler=dict(type=DefaultSampler, shuffle=True),
    collate_fn=dict(type=default_collate_fn))

#######################################################################
#                    PART 4  Scheduler & Optimizer                    #
#######################################################################
# optimizer
optim_wrapper = dict(
    type=AmpOptimWrapper,
    optimizer=dict(
        type=optim_type, lr=lr, betas=betas, weight_decay=weight_decay),
    clip_grad=dict(max_norm=max_norm, error_if_nonfinite=False),
    accumulative_counts=accumulative_counts,
    loss_scale='dynamic',
    dtype='float16')

# learning policy
# More information: https://github.com/open-mmlab/mmengine/blob/main/docs/en/tutorials/param_scheduler.md  # noqa: E501
param_scheduler = dict(
    type=CosineAnnealingLR,
    eta_min=lr * 0.1,
    by_epoch=True,
    T_max=max_epochs,
    convert_to_iter_based=True)

# train, val, test setting
train_cfg = dict(by_epoch=True, max_epochs=max_epochs, val_interval=1)

#######################################################################
#                           PART 5  Runtime                           #
#######################################################################
# Log the dialogue periodically during the training process, optional
custom_hooks = [
    dict(type=DatasetInfoHook, tokenizer=tokenizer),
    dict(
        type=EvaluateChatHook,
        tokenizer=tokenizer,
        every_n_iters=evaluation_freq,
        evaluation_inputs=evaluation_inputs,
        instruction=prompt_template.INSTRUCTION_START)
]

# configure default hooks
default_hooks = dict(
    # record the time of every iteration.
    timer=dict(type=IterTimerHook),
    # print log every 100 iterations.
    logger=dict(type=LoggerHook, interval=10),
    # enable the parameter scheduler.
    param_scheduler=dict(type=ParamSchedulerHook),
    # save checkpoint per epoch.
    checkpoint=dict(type=CheckpointHook, interval=1),
    # set sampler seed in distributed evrionment.
    sampler_seed=dict(type=DistSamplerSeedHook),
)

# configure environment
env_cfg = dict(
    # whether to enable cudnn benchmark
    cudnn_benchmark=False,
    # set multi process parameters
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    # set distributed parameters
    dist_cfg=dict(backend='nccl'),
)

# set visualizer
visualizer = None

# set log level
log_level = 'INFO'

# load from which checkpoint
load_from = None

# whether to resume training from the loaded checkpoint
resume = False

# Defaults to use random seed and disable `deterministic`
randomness = dict(seed=None, deterministic=False)
```
报错内容
```
[2023-08-31 12:23:17,914] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.10.1, git-hash=unknown, git-branch=unknown
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 5406) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
/app/xtuner/tools/train.py FAILED
----------------------------------------------------
```
去掉 deepspeed 启动可以正常训练。
```
NPROC_PER_NODE=2 xtuner train /app/train/internlm_7b_qlora_alpaca_zh_e3/internlm_7b_qlora_alpaca_zh_e3.py
```

```
08/31 13:44:01 - mmengine - INFO - Epoch(train) [1][ 260/2037]  lr: 1.9920e-04  eta: 1 day, 1:44:18  time: 16.2497  data_time: 0.0056  memory: 12276  loss: 1.9615  grad_norm: 0.0383
08/31 13:46:34 - mmengine - INFO - Epoch(train) [1][ 270/2037]  lr: 1.9914e-04  eta: 1 day, 1:39:49  time: 15.3228  data_time: 0.0058  memory: 12276  loss: 1.9860  grad_norm: 0.0383
08/31 13:49:17 - mmengine - INFO - Epoch(train) [1][ 280/2037]  lr: 1.9908e-04  eta: 1 day, 1:38:43  time: 16.2589  data_time: 0.0056  memory: 12276  loss: 1.9858  grad_norm: 0.0371
08/31 13:51:59 - mmengine - INFO - Epoch(train) [1][ 290/2037]  lr: 1.9901e-04  eta: 1 day, 1:37:35  time: 16.2844  data_time: 0.0059  memory: 12276  loss: 1.8885  grad_norm: 0.0364
08/31 13:54:33 - mmengine - INFO - Epoch(train) [1][ 300/2037]  lr: 1.9894e-04  eta: 1 day, 1:33:13  time: 15.3157  data_time: 0.0058  memory: 12276  loss: 1.9689  grad_norm: 0.0364
08/31 13:57:15 - mmengine - INFO - Epoch(train) [1][ 310/2037]  lr: 1.9887e-04  eta: 1 day, 1:31:48  time: 16.2196  data_time: 0.0055  memory: 12276  loss: 1.9434  grad_norm: 0.0355
```

**Comment by LZHgrla** [comment]
目前来看问题并不是因为显存不足，同时我在两张T4上能够正常启动DeepSpeed训练

目前怀疑是DeepSpeed安装的问题，建议您可以尝试使用命令`ds_report`检查一下是否有错误？

如果上述命令一切正常，可以尝试运行一些DeepSpeed官方提供的examples脚本，如[DeepSpeed_CIFAR](https://github.com/microsoft/DeepSpeedExamples/tree/master/training/cifar)，验证DeepSpeed能否正常启动～

**Comment by liuwake** [comment]
> 目前来看并不是因为显存不足，同时我在两张T4上能够正常启动DeepSpeed训练
> 
> 怀疑是DeepSpeed安装的问题，建议您可以尝试使用命令`ds_report`检查一下是否有错误？
> 
> 如果上述命令一切正常，可以尝试运行一些DeepSpeed官方提供的examples脚本，如[DeepSpeed_CIFAR](https://github.com/microsoft/DeepSpeedExamples/tree/master/training/cifar)，验证DeepSpeed能否正常启动～

-  佬的方法有效!解决了我同样的问题:[无法启动训练，似乎是mmengine有问题 #691](https://github.com/InternLM/xtuner/issues/691)
