### ISSUE TITLE
使用Xtuner微调baichuan2-13b-chat报错

### ISSUE THREAD

**Issue by wangkz2023** [InternLM/xtuner#800]
报错信息
Traceback (most recent call last):
  File "/home/kpxuegroup/wangkz23/LLM/Xtuner/xtuner/xtuner/tools/train.py", line 360, in <module>
    main()
  File "/home/kpxuegroup/wangkz23/LLM/Xtuner/xtuner/xtuner/tools/train.py", line 349, in main
    runner = Runner.from_cfg(cfg)
  File "/home/kpxuegroup/wangkz23/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/kpxuegroup/wangkz23/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/home/kpxuegroup/wangkz23/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/home/kpxuegroup/wangkz23/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/kpxuegroup/wangkz23/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/kpxuegroup/wangkz23/miniconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/kpxuegroup/wangkz23/LLM/Xtuner/xtuner/xtuner/model/sft.py", line 93, in __init__
    dispatch_modules(self.llm, use_varlen_attn=use_varlen_attn)
  File "/home/kpxuegroup/wangkz23/LLM/Xtuner/xtuner/xtuner/model/modules/dispatch/__init__.py", line 266, in dispatch_modules
    check(type(model).__name__)
  File "/home/kpxuegroup/wangkz23/LLM/Xtuner/xtuner/xtuner/model/modules/dispatch/__init__.py", line 261, in check
    assert TRANSFORMERS_VERSION >= LOWEST_TRANSFORMERS_VERSION[
KeyError: 'BaichuanForCausalLM'

**Comment by wsa-dhu** [comment]
已解决，看我的新问题

**Comment by wangkz2023** [comment]
十分感谢您的回复 @wsa-dhu
