### ISSUE TITLE
训练intermLM2_5_7b报错

### ISSUE THREAD

**Issue by SingL3** [InternLM/xtuner#811]
```
[32mpt-p1wvaor8-worker-0 logs:[0m 07/05 15:59:30 - mmengine - WARNING - Dataset Dataset has no metainfo. ``dataset_meta`` in visualizer will be None.
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]: Traceback (most recent call last):
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/home/linjunpeng/reranker_llm/xtuner/xtuner/tools/train.py", line 360, in <module>
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     main()
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/home/linjunpeng/reranker_llm/xtuner/xtuner/tools/train.py", line 356, in main
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     runner.train()
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llmreranker/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1182, in train
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     self.strategy.prepare(
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llmreranker/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 381, in prepare
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     model = self.build_model(model)
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llmreranker/lib/python3.10/site-packages/mmengine/_strategy/base.py", line 306, in build_model
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     model = MODELS.build(model)
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llmreranker/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     return self.build_func(cfg, *args, **kwargs, registry=self)
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llmreranker/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     return build_from_cfg(cfg, registry, default_args)
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llmreranker/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     obj = obj_cls(**args)  # type: ignore
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/home/linjunpeng/reranker_llm/xtuner/xtuner/model/sft.py", line 84, in __init__
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     llm = self._dispatch_lm_model_cfg(llm, max_position_embeddings)
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/home/linjunpeng/reranker_llm/xtuner/xtuner/model/sft.py", line 225, in _dispatch_lm_model_cfg
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     llm_cfg = AutoConfig.from_pretrained(
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llmreranker/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 974, in from_pretrained
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     config_class = get_class_from_dynamic_module(
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llmreranker/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 514, in get_class_from_dynamic_module
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     return get_class_in_module(class_name, final_module)
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llmreranker/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 213, in get_class_in_module
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]:     return getattr(module, class_name)
[32mpt-p1wvaor8-worker-0 logs:[0m [rank2]: AttributeError: module 'transformers_modules.internlm2_5-7b.configuration_internlm2' has no attribute 'InternLM2Config'

```
确认intermLM2.5为当前hf最新版本

**Comment by SingL3** [comment]
transformers版本4.42.1，更换4.41.0后正常。

**Comment by SingL3** [comment]
新的错误：
```
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]: Traceback (most recent call last):
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:   File "/mnt/home/xxxxxxxx/llm/xtuner/xtuner/tools/train.py", line 360, in <module>
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:     main()
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:   File "/mnt/home/xxxxxxxx/llm/xtuner/xtuner/tools/train.py", line 356, in main
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:     runner.train()
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llm/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1182, in train
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:     self.strategy.prepare(
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llm/lib/python3.10/site-packages/mmengine/_strategy/deepspeed.py", line 394, in prepare
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:     self.param_schedulers = self.build_param_scheduler(
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llm/lib/python3.10/site-packages/mmengine/_strategy/base.py", line 658, in build_param_scheduler
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:     param_schedulers = self._build_param_scheduler(
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llm/lib/python3.10/site-packages/mmengine/_strategy/base.py", line 563, in _build_param_scheduler
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:     PARAM_SCHEDULERS.build(
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llm/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:     return self.build_func(cfg, *args, **kwargs, registry=self)
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llm/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 294, in build_scheduler_from_cfg
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:     return scheduler_cls.build_iter_from_epoch(  # type: ignore
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llm/lib/python3.10/site-packages/mmengine/optim/scheduler/param_scheduler.py", line 787, in build_iter_from_epoch
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:     return cls(*args, begin=begin, end=end, by_epoch=by_epoch, **kwargs)
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llm/lib/python3.10/site-packages/mmengine/optim/scheduler/lr_scheduler.py", line 20, in __init__
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:     super().__init__(optimizer, 'lr', *args, **kwargs)
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llm/lib/python3.10/site-packages/mmengine/optim/scheduler/param_scheduler.py", line 759, in __init__
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:     super().__init__(
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:   File "/mnt/data/conda/envs/llm/lib/python3.10/site-packages/mmengine/optim/scheduler/param_scheduler.py", line 68, in __init__
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]:     raise ValueError('end should be larger than begin, but got'
[32mpt-5vf2t9a1-worker-0 logs:[0m [rank2]: ValueError: end should be larger than begin, but got begin=0, end=0
```
log中scheduler：
```
[32mpt-5vf2t9a1-worker-0 logs:[0m param_scheduler = [
[32mpt-5vf2t9a1-worker-0 logs:[0m     dict(
[32mpt-5vf2t9a1-worker-0 logs:[0m         begin=0,
[32mpt-5vf2t9a1-worker-0 logs:[0m         by_epoch=True,
[32mpt-5vf2t9a1-worker-0 logs:[0m         convert_to_iter_based=True,
[32mpt-5vf2t9a1-worker-0 logs:[0m         end=0.12,
[32mpt-5vf2t9a1-worker-0 logs:[0m         start_factor=0.025,
[32mpt-5vf2t9a1-worker-0 logs:[0m         type='mmengine.optim.LinearLR'),
[32mpt-5vf2t9a1-worker-0 logs:[0m     dict(
[32mpt-5vf2t9a1-worker-0 logs:[0m         begin=0.12,
[32mpt-5vf2t9a1-worker-0 logs:[0m         by_epoch=True,
[32mpt-5vf2t9a1-worker-0 logs:[0m         convert_to_iter_based=True,
[32mpt-5vf2t9a1-worker-0 logs:[0m         end=4,
[32mpt-5vf2t9a1-worker-0 logs:[0m         eta_min=1.0000000000000002e-06,
[32mpt-5vf2t9a1-worker-0 logs:[0m         type='mmengine.optim.CosineAnnealingLR'),
```
