### ISSUE TITLE
跑llama3_8b_full_alpaca_e3时，loss为nan

### ISSUE THREAD

**Issue by heya5** [InternLM/xtuner#841]
命令
```bash
NPROC_PER_NODE=8 xtuner train llama3_8b_full_alpaca_e3 --deepspeed deepspeed_zero2
```

报错:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/a100user/llm_train_eval/experiments/exp04/xtuner/xtuner/tools/train.py", line 360, in <module>
[rank0]:     main()
[rank0]:   File "/home/a100user/llm_train_eval/experiments/exp04/xtuner/xtuner/tools/train.py", line 356, in main
[rank0]:     runner.train()
[rank0]:   File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1200, in train
[rank0]:     model = self.train_loop.run()  # type: ignore
[rank0]:   File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/loops.py", line 287, in run
[rank0]:     self.run_iter(data_batch)
[rank0]:   File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/loops.py", line 314, in run_iter
[rank0]:     self.runner.call_hook(
[rank0]:   File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/mmengine/runner/_flexible_runner.py", line 1271, in call_hook
[rank0]:     getattr(hook, fn_name)(self, **kwargs)
[rank0]:   File "/home/a100user/llm_train_eval/experiments/exp04/xtuner/xtuner/engine/hooks/evaluate_chat_hook.py", line 271, in after_train_iter
[rank0]:     self._generate_samples(runner, save_eval_output=save_eval_output)
[rank0]:   File "/home/a100user/llm_train_eval/experiments/exp04/xtuner/xtuner/engine/hooks/evaluate_chat_hook.py", line 223, in _generate_samples
[rank0]:     self._eval_language(runner, model, device, max_new_tokens,
[rank0]:   File "/home/a100user/llm_train_eval/experiments/exp04/xtuner/xtuner/engine/hooks/evaluate_chat_hook.py", line 181, in _eval_language
[rank0]:     generation_output = model.generate(
[rank0]:   File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1914, in generate
[rank0]:     result = self._sample(
[rank0]:   File "/root/miniconda3/envs/xtuner-env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2693, in _sample
[rank0]:     next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
[rank0]: RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

查log发现第20个step打的loss就变nan了
```bash
07/15 11:07:44 - mmengine - INFO - Iter(train) [ 10/795]  lr: 8.1819e-06  eta: 0:10:38  time: 0.8139  data_time: 0.0040  memory: 26677  loss: 1.8250
07/15 11:07:52 - mmengine - INFO - Iter(train) [ 20/795]  lr: 1.7273e-05  eta: 0:10:35  time: 0.8271  data_time: 0.0042  memory: 34481  loss: nan
07/15 11:08:00 - mmengine - INFO - Iter(train) [ 30/795]  lr: 1.9997e-05  eta: 0:10:22  time: 0.8002  data_time: 0.0041  memory: 34337  loss: nan
```

**Comment by Echo0125** [comment]
maybe，试试zero1或者zero3，zero2貌似有bug~

**Comment by heya5** [comment]
模型改成bf16可以解决
