### ISSUE TITLE
自定义map_fn无法加载，报错：'package' argument is required to perform a relative import for '.custom_map_fn'

### ISSUE THREAD

**Issue by iFe1er** [InternLM/xtuner#97]
用法参考了文档：https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/single_turn_conversation.md

在./定义了映射函数文件custom_adcompcot_map_fn.py，并在自定义的config中进行了import:

from .custom_adcompcot_map_fn import custom_map_fn

运行train的时候报错，报错信息如下：

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/lazy.py", line 68, in build
    module = importlib.import_module(self._module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 121, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.custom_adcompcot_map_fn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xtuner/tools/train.py", line 225, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/xtuner/tools/train.py", line 221, in main
    runner.train()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 1703, in train
    self._train_loop = self.build_train_loop(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 1502, in build_train_loop
    loop = EpochBasedTrainLoop(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 1353, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 135, in __getitem__
    return self.build_lazy(super().__getitem__(key))
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 214, in build_lazy
    value = value.build()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/lazy.py", line 70, in build
    raise type(e)(f'Failed to import {self._module} '
TypeError: Failed to import .custom_adcompcot_map_fn in ./qwen_7b_chat_custom_AdCompCoT_e1.py, line 17 for the 'package' argument is required to perform a relative import for '.custom_adcompcot_map_fn'

**Comment by HIT-cwh** [comment]
不好意思给您的使用带来不便。文档可能需要修改一下，如果是import已经写好的map_fn的话，需要
```
from mmengine import read_base
with read_base():
    from .custom_adcompcot_map_fn import custom_map_fn
```
我们尽快update下文档，感谢您指出的问题！

**Comment by liuyanyi** [comment]
加了read_base会有config格式化的报错
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/yapf/pytree/pytree_utils.py", line 113, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/local/lib/python3.10/dist-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 188, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/local/lib/python3.10/dist-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 157, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/local/lib/python3.10/dist-packages/yapf_third_party/_ylib2to3/pgen2/parse.py", line 230, in addtoken
    return self._addtoken(ilabel, type, value, context)
  File "/usr/local/lib/python3.10/dist-packages/yapf_third_party/_ylib2to3/pgen2/parse.py", line 313, in _addtoken
    raise ParseError('bad input', type, value, context)
yapf_third_party._ylib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (65, 15))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/yapf/yapflib/yapf_api.py", line 206, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/usr/local/lib/python3.10/dist-packages/yapf/pytree/pytree_utils.py", line 116, in ParseCodeToTree
    ast.parse(code)
  File "/usr/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 65
    med_sft_map_fn=<function med_sft_map_fn at 0x7f2acbc5c0d0>
                   ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 1475, in pretty_text
    text, _ = FormatCode(
  File "/usr/local/lib/python3.10/dist-packages/yapf/yapflib/yapf_api.py", line 209, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
yapf.yapflib.errors.YapfError: <unknown>:65:16: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/xtuner/xtuner/tools/train.py", line 225, in <module>
    main()
  File "/workspace/xtuner/xtuner/tools/train.py", line 214, in main
    runner = Runner.from_cfg(cfg)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 445, in from_cfg
    runner = cls(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 386, in __init__
    self._log_env(env_cfg)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 2356, in _log_env
    self.logger.info(f'Config:\n{self.cfg.pretty_text}')
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 1478, in pretty_text
    raise SyntaxError('Failed to format the config file, please '
SyntaxError: Failed to format the config file, please check the syntax of: 
```


Full Config:
```
# Copyright (c) OpenMMLab. All rights reserved.
import torch
from bitsandbytes.optim import PagedAdamW32bit
from datasets import load_dataset
from mmengine.dataset import DefaultSampler
from mmengine.hooks import (CheckpointHook, DistSamplerSeedHook, IterTimerHook,
                            LoggerHook, ParamSchedulerHook)
from mmengine.optim import AmpOptimWrapper, CosineAnnealingLR
from peft import LoraConfig
from transformers import (AutoModelForCausalLM, AutoTokenizer,
                          BitsAndBytesConfig)

from xtuner.dataset import process_hf_dataset
from mmengine import read_base

from xtuner.dataset.collate_fns import default_collate_fn
from xtuner.dataset.map_fns import template_map_fn_factory
from xtuner.engine import DatasetInfoHook, EvaluateChatHook
from xtuner.model import SupervisedFinetune
from xtuner.utils import PROMPT_TEMPLATE

from med_sft.med_sft_map_fn import med_sft_map_fn

#######################################################################
#                          PART 1  Settings                           #
#######################################################################
# Model
pretrained_model_name_or_path = '/datasets/Qwen-7B/'

# Data
data_path = '/datasets/DISC-Med-SFT/'
data_config_name = None
# data_config_name = 'finetune'
prompt_template = PROMPT_TEMPLATE.qwen_chat
max_length = 2048
pack_to_max_length = True

# Scheduler & Optimizer
batch_size = 2  # per_device
accumulative_counts = 16
dataloader_num_workers = 0
max_epochs = 1
optim_type = PagedAdamW32bit
lr = 2e-4
betas = (0.9, 0.999)
weight_decay = 0
max_norm = 1  # grad clip

# Evaluate the generation performance during the training
evaluation_freq = 500
evaluation_inputs = [
    '我有家族遗传性的过敏，请问可以可以献血吗？', '我爷爷有高血压，请问他可以喝咖啡吗？',
    '我女儿今年3岁了，从昨天晚上九点开始腹泻，到现在已经八个小时了，请问应该怎么办？'
]

#######################################################################
#                      PART 2  Model & Tokenizer                      #
#######################################################################
tokenizer = dict(
    type=AutoTokenizer.from_pretrained,
    pretrained_model_name_or_path=pretrained_model_name_or_path,
    trust_remote_code=True,
    padding_side='right')

model = dict(
    type=SupervisedFinetune,
    llm=dict(
        type=AutoModelForCausalLM.from_pretrained,
        pretrained_model_name_or_path=pretrained_model_name_or_path,
        trust_remote_code=True,
        torch_dtype=torch.float16,
        quantization_config=dict(
            type=BitsAndBytesConfig,
            load_in_4bit=True,
            load_in_8bit=False,
            llm_int8_threshold=6.0,
            llm_int8_has_fp16_weight=False,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type='nf4')),
    lora=dict(
        type=LoraConfig,
        r=64,
        lora_alpha=16,
        lora_dropout=0.1,
        bias='none',
        task_type='CAUSAL_LM'))

#######################################################################
#                      PART 3  Dataset & Dataloader                   #
#######################################################################
train_dataset = dict(
    type=process_hf_dataset,
    dataset=dict(type=load_dataset, path=data_path, name=data_config_name),
    tokenizer=tokenizer,
    max_length=max_length,
    dataset_map_fn=med_sft_map_fn,
    template_map_fn=dict(
        type=template_map_fn_factory, template=prompt_template),
    remove_unused_columns=True,
    shuffle_before_pack=True,
    pack_to_max_length=pack_to_max_length)

train_dataloader = dict(
    batch_size=batch_size,
    num_workers=dataloader_num_workers,
    dataset=train_dataset,
    sampler=dict(type=DefaultSampler, shuffle=True),
    collate_fn=dict(type=default_collate_fn))

#######################################################################
#                    PART 4  Scheduler & Optimizer                    #
#######################################################################
# optimizer
optim_wrapper = dict(
    type=AmpOptimWrapper,
    optimizer=dict(
        type=optim_type, lr=lr, betas=betas, weight_decay=weight_decay),
    clip_grad=dict(max_norm=max_norm, error_if_nonfinite=False),
    accumulative_counts=accumulative_counts,
    loss_scale='dynamic',
    dtype='float16')

# learning policy
# More information: https://github.com/open-mmlab/mmengine/blob/main/docs/en/tutorials/param_scheduler.md  # noqa: E501
param_scheduler = dict(
    type=CosineAnnealingLR,
    eta_min=lr * 0.1,
    by_epoch=True,
    T_max=max_epochs,
    convert_to_iter_based=True)

# train, val, test setting
train_cfg = dict(by_epoch=True, max_epochs=max_epochs, val_interval=1)

#######################################################################
#                           PART 5  Runtime                           #
#######################################################################
# Log the dialogue periodically during the training process, optional
custom_hooks = [
    dict(type=DatasetInfoHook, tokenizer=tokenizer),
    dict(
        type=EvaluateChatHook,
        tokenizer=tokenizer,
        every_n_iters=evaluation_freq,
        stop_word='<|im_end|>',
        evaluation_inputs=evaluation_inputs,
        instruction=prompt_template.INSTRUCTION_START)
]

# configure default hooks
default_hooks = dict(
    # record the time of every iteration.
    timer=dict(type=IterTimerHook),
    # print log every 100 iterations.
    logger=dict(type=LoggerHook, interval=10),
    # enable the parameter scheduler.
    param_scheduler=dict(type=ParamSchedulerHook),
    # save checkpoint per epoch.
    checkpoint=dict(type=CheckpointHook, interval=1),
    # set sampler seed in distributed evrionment.
    sampler_seed=dict(type=DistSamplerSeedHook),
)

# configure environment
env_cfg = dict(
    # whether to enable cudnn benchmark
    cudnn_benchmark=False,
    # set multi process parameters
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    # set distributed parameters
    dist_cfg=dict(backend='nccl'),
)

# set visualizer
visualizer = None

# set log level
log_level = 'INFO'

# load from which checkpoint
load_from = None

# whether to resume training from the loaded checkpoint
resume = False

# Defaults to use random seed and disable `deterministic`
randomness = dict(seed=None, deterministic=False)

```

**Comment by HIT-cwh** [comment]
> 不好意思给您的使用带来不便。刚刚发现mmengine当前版本尚不支持在config文件中通过相对路径的方式import进来python object（即`from .custom_adcompcot_map_fn import custom_map_fn`），如果您着急使用，可以git clone下来xtuner，再：
> 
> 1. 将您写好的`custom_adcompcot_map_fn.py`文件放到`xtuner/dataset/map_fns/dataset_map_fns/`目录里；
> 2. 在`xtuner/dataset/map_fns/dataset_map_fns/__init__.py`里import进来您实现的`custom_map_fn`。
> 
> 这样就可以在config文件中正常import `custom_map_fn`了。下一个mmengine版本应该会支持 “在config文件中通过相对路径的方式import进来python object” 这一功能。
> 
> 感谢您指出的问题！

昨天下午的时候我们也debug发现这个问题了，之后重新编辑了一下这条回复。麻烦您再按照这个方式import下试试呢？


或者您看下我刚刚给mmengine提的一个[pr](https://github.com/open-mmlab/mmengine/pull/1344)，按照这个pr的方法修改下[mmengine的对应文件](https://github.com/open-mmlab/mmengine/blob/main/mmengine/config/config.py#L47-L56)，再在您的config文件里用下面的方法import进来您实现的map function应该就可以了：

```
from mmengine import read_base
with read_base():
    from med_sft.med_sft_map_fn import med_sft_map_fn
############### other config ##################
```

**Comment by pppppM** [comment]
@iFe1er @liuyanyi 这个 bug 在 #101 中被修复

现在可以直接通过下面这种方式导入，不需 mmengine

```
from mmengine import read_base
with read_base():
    from med_sft.med_sft_map_fn import med_sft_map_fn
############### other config ##################
```
