### ISSUE TITLE
Qwen-7B-chat colab GPU memory not enough，改为int4版模型后报错

### ISSUE THREAD

**Issue by iFe1er** [InternLM/xtuner#99]
用自定义的单轮数据训练Qwen-7B，colab(配置T4，15GB内存）报错CUDA OOM。

1. 案例中，InternLM-7B可以正常微调，同样7B的模型为什么Qwen无法实现呢，请问有什么方法能降低显存需要吗？
模型配置如下
model = dict(
    type=SupervisedFinetune,
    llm=dict(
        type=AutoModelForCausalLM.from_pretrained,
        pretrained_model_name_or_path=pretrained_model_name_or_path,
        trust_remote_code=True,
        torch_dtype=torch.float16,
        quantization_config=dict(
            type=BitsAndBytesConfig,
            load_in_4bit=True,
            load_in_8bit=False,
            llm_int8_threshold=6.0,
            llm_int8_has_fp16_weight=False,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type='nf4')),
    lora=dict(
        type=LoraConfig,
        r=64,
        lora_alpha=16,
        lora_dropout=0.1,
        bias='none',
        task_type='CAUSAL_LM'))

2.  尝试将'Qwen/Qwen-7B-Chat'改为'Qwen/Qwen-7B-Chat-Int4'，报错:

Downloading (…)lve/main/config.json: 100% 1.20k/1.20k [00:00<00:00, 6.91MB/s]
Downloading (…)onfiguration_qwen.py: 100% 2.09k/2.09k [00:00<00:00, 13.6MB/s]
A new version of the following files was downloaded from https://huggingface.co/Qwen/Qwen-7B-Chat-Int4:
- configuration_qwen.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Downloading (…)ain/modeling_qwen.py: 100% 47.1k/47.1k [00:00<00:00, 5.05MB/s]
Downloading (…)_generation_utils.py: 100% 14.6k/14.6k [00:00<00:00, 70.7MB/s]
A new version of the following files was downloaded from https://huggingface.co/Qwen/Qwen-7B-Chat-Int4:
- qwen_generation_utils.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/Qwen/Qwen-7B-Chat-Int4:
- modeling_qwen.py
- qwen_generation_utils.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xtuner/tools/train.py", line 225, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/xtuner/tools/train.py", line 214, in main
    runner = Runner.from_cfg(cfg)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 445, in from_cfg
    runner = cls(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 412, in __init__
    self.model = self.build_model(model)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 819, in build_model
    model = MODELS.build(model)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/xtuner/model/sft.py", line 24, in __init__
    self.llm = self._build_from_cfg_or_module(llm)
  File "/usr/local/lib/python3.10/dist-packages/xtuner/model/sft.py", line 76, in _build_from_cfg_or_module
    return BUILDER.build(cfg_or_mod)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2556, in from_pretrained
    loading_attr_dict = quantization_config.get_loading_attributes()
AttributeError: 'BitsAndBytesConfig' object has no attribute 'get_loading_attributes'

**Comment by pppppM** [comment]
可以尝试调低 `max_length`，或者直接使用 qwen_7b_chat_qlora_oasst1_512_e3
https://github.com/InternLM/xtuner/blob/6e44d6b3933d2bafc513b4541ab9bec5a2871f01/xtuner/configs/qwen/qwen_7b_chat/qwen_7b_chat_qlora_oasst1_512_e3.py#L29

**Comment by iFe1er** [comment]
> 

感谢快速回复，测试max_length在1200左右可以正常运行了，不过部分样本可能会被截断

另外，是否暂无法支持Qwen-7B-Chat-Int4，quantization_config能进行针对性修改来降低显存需要吗

**Comment by pppppM** [comment]
Qwen-7B-Chat-Int4 是指？quantization_config 没有什么参数可以调节了，如果想进一步降低显存，可以使用 deepspeed zero2，使用方法是在训练命令后加 --deepspeed deepspeed_zero2

另外，样本被截断，可能是开启了 pack_max_lenght，会将多条数据拼接起来，如果最后一条数据超长了，会被截断，这个操作能最大化地利用 GPU，训练会比较快


如果不想数据被截断，可以设为 False，这样训练会慢一些
